### ISSUE TITLE
!isClosed "You cannot add event to closed Stream"  Error when using GetX or Obx Widget

### ISSUE THREAD

**Issue by SivaramNalliboyana** [jonataslaw/getx#1222]
**Describe the bug**
I have a api which queries all the posts and I am showing them in the frontend with GetX. Everything is fine, the like or save functionalities are working perfectly. But whenever I go to a new page route, which has a GetX Widget or Obx Widget and come back again and try to like the post, I get that error "!isClosed "You cannot add event to closed Stream" . The interesting thing is that, when the page I want to go has a GetBuilder Widget , the error does not occur

**Reproduction code:

**HomeController**
```dart
class HomeController extends GetxController {
  var postsList= <Rx<Post>>[].obs;
  ApiService apiService = ApiService();

  @override
  void onInit() {
    fetchPosts();
    super.onInit();
  }

  Future<void> fetchPosts() async {
    var posts= await apiService.getapidata('${postsurl}/feed');
    var postslist= postFromJson(posts);
    if (postslist!= null) {
      postsList.assignAll(postslist.map((item) => item.obs).toList());
    }
  }
}

```
**HomeScreen with the posts**
```dart
class HomeScreen extends StatelessWidget {
  final HomeController homeController =
      Get.put(HomeController(), permanent: true);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Obx(
        () => RefreshIndicator(
          onRefresh: () => homeController.fetchPosts(),
          child: ListView.builder(
            itemCount: homeController.postsList.length,
            itemBuilder: (context, index) {
              return PostWidget(homeController.postsList[index], index);
            },
          ),
        ),
      ),
    );
  }
}
```
**My Post Widget where I display the image and like the post**
```dart
class PostWidget extends StatelessWidget {
  final Rx<Post> post;
  final int index;
  ApiService apiService = ApiService();
  PostWidget(this.post, this.index);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(color: Colors.white),
      child: Column(
        children: [
          AspectRatio(
              aspectRatio: 1 / 1,
              child: InkWell(
                onTap: () => Get.to(() => SampleScreen()), // Here I go to the sample screen
                child: Image(
                  image: NetworkImage(
                    post.value.image,
                  ),
                  fit: BoxFit.fill,
                ),
              )),
          Padding(
            padding: const EdgeInsets.only(top: 10, left: 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    InkWell(
                      onTap: () async {     // SO HERE I LIKE THE POST
                        bool usersmiled = post.value.userSmiled;
                        usersmiled
                            ? post.update((p) => p.post--)
                            : post.update((p) => p.post++);
                        post.update((p) => p.userSmiled = !p.userSmiled);
                      
                      },
                      child: Obx(
                        () => Container(
                          decoration: BoxDecoration(
                              color: post.value.userSmiled
                                  ? yellow
                                  : Colors.grey[350],
                              borderRadius: BorderRadius.circular(20)),
                          child: Padding(
                            padding: const EdgeInsets.only(
                                left: 10, right: 20, top: 10, bottom: 10),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(
                                  Icons.favourite,
                                  size: 32,
                                ),
                                SizedBox(
                                  width: 10,
                                ),
                                Text(
                                  post.value.smiles.toString(),
                                  style: mystyle(
                                      19, Colors.black, FontWeight.w600),
                                ),
                              ],
                            ),
                          ),
                        ),
            
}
```
** The screen where I am navigating. Now when I use a GetX Widget here and pop out the current route and try to like the post, I have that bad state error
```dart
class SampleScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetX<ViewProfileController>(     // Here I use the GetX Widget
        init: ViewProfileController(),
        builder: (controller) => Text("hi"),
      ),
    );
  }
}
```
**But when I use a GetBuilder in the SampleScreen I dont have that error when I go back and like the post**

**THE FULL ERROR**
```
E/flutter (20694): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:get/get_rx/src/rx_stream/get_stream.dart': Failed assertion: line 95 pos 12: '!isClosed': You cannot add event to closed Stream
E/flutter (20694): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (20694): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (20694): #2      GetStream.add
package:get/…/rx_stream/get_stream.dart:95
E/flutter (20694): #3      GetStream._notifyData
package:get/…/rx_stream/get_stream.dart:47
E/flutter (20694): #4      GetStream.add
package:get/…/rx_stream/get_stream.dart:97
E/flutter (20694): #5      _RxImpl.update
package:get/…/rx_core/rx_impl.dart:198
E/flutter (20694): #6      PostWidget.build.<anonymous closure>
package:memesapp/…/home/widgets.dart:52
E/flutter (20694): #7      PostWidget.build.<anonymous closure>
package:memesapp/…/home/widgets.dart:49
E/flutter (20694): #8      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:991
E/flutter (20694): #9      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
E/flutter (20694): #10     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:607
E/flutter (20694): #11     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
E/flutter (20694): #12     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:267
E/flutter (20694): #13     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
E/flutter (20694): #14     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:385
E/flutter (20694): #15     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:361
E/flutter (20694): #16     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:278
E/flutter (20694): #17     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:316
E/flutter (20694): #18     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:280
E/flutter (20694): #19     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:238
E/flutter (20694): #20     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:221
E/flutter (20694): #22     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (20694): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (20694): #24     _invoke1 (dart:ui/hooks.dart:180:10)
E/flutter (20694): #25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
E/flutter (20694): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

```

**Comment by SivaramNalliboyana** [comment]
Could anyone help me please, I am still stuck with this issue

**Comment by jonataslaw** [comment]
This is not an error, it is a warning, and it occurs when you insert GetBuilder and Rx variables without using MixinBuilder, because GetBuilder closes the controller, which for a few milliseconds is still connected to a GetX/Obx.

**Comment by SivaramNalliboyana** [comment]
Hi jontas, thank you for the reply. But could you guide me , how can I implement the MixinBuilder, or could you just tell me where to use it. I am a bit confused now, where to implement it

**Comment by SivaramNalliboyana** [comment]
And also, I never use getbuilder and rxvariables together

**Comment by eduardoflorence** [comment]
> Hi jontas, thank you for the reply. But could you guide me , how can I implement the MixinBuilder, or could you just tell me where to use it. I am a bit confused now, where to implement it

@SivaramNalliboyana, see my example here: https://gist.github.com/eduardoflorence/cc664ebae5142358de39df2a3a98e6df

**Comment by SivaramNalliboyana** [comment]
Jontas please, could you help me. I am still stuck, I have no clue right now
