### ISSUE TITLE
flutter getx issue when using use get.back() twice

### ISSUE THREAD

**Issue by webeasystep** [jonataslaw/getx#1293]
I have two Pages (Login,Register) , and I have a button on the Login Page To Go to the Register Button And Another button to go back to the Login Page.

when I Go to the Register Page in the first time and try to go back there is no problem but when try again , it will display this issue , although i use binding correctly .

Flutter Version : 2.0.4 
Getx Version : 4.1.3

**Reproduction code
```
Performing hot restart...
Syncing files to device sdk gphone x86...
Restarted application in 3,163ms.
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /register_page
[GETX] Instance "RegisterController" has been created
[GETX] Instance "RegisterController" has been initialized
[GETX] CLOSE TO ROUTE /register_page
[GETX] "RegisterController" onDelete() called
[GETX] "RegisterController" deleted from memory
[GETX] GOING TO ROUTE /register_page

======== Exception caught by widgets library =======================================================
The following message was thrown building Obx(dirty, state: _ObxState#ece44):
"RegisterController" not found. You need to call "Get.put(RegisterController())" or "Get.lazyPut(()=>RegisterController())"

The relevant error-causing widget was: 
  Obx file:///D:/projects/talab/lib/modules/users/views/register_page.dart:43:22
When the exception was thrown, this was the stack: 
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:332:7)
#1      GetView.controller (package:get/get_state_manager/src/simple/get_view.dart:38:37)
#2      RegisterPage.build.<anonymous closure>.<anonymous closure> (package:talab/modules/users/views/register_page.dart:48:32)
#3      Obx.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:84:28)
#4      _ObxState.notifyChilds (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:52:27)
...
=====================================================================================MY code
class AppPages {
  static const INITIAL = AppRoutes.RootURL;

  static final routes = [

    //Simple GetPage
    GetPage(
      name: AppRoutes.LoginPageURL,
      page: () => LoginPage(),
      binding: BindingsBuilder (() => Get.lazyPut(() => LoginController ())),
      parameter: {},
      middlewares: [],
      children: [],
    ),
    GetPage(
      name: AppRoutes.RegisterPageURL,
      page: () => RegisterPage(),
      binding: BindingsBuilder(() => Get.lazyPut(() => RegisterPage())),
     ),

  ];
}

Register Page
==============
class RegisterPage extends GetView<RegisterController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.whiteColor,
      appBar: AppBar(
        backgroundColor: AppColors.whiteColor,
        elevation: 0,
        bottomOpacity: 0.0,
        toolbarHeight: 80,
        leading: Padding(
          padding: EdgeInsets.all(8.0),
          child:  Material(
            color: AppColors.primaryColor,
            child: IconButton(
              icon: Icon(
                Icons.arrow_back_ios_outlined,
                size: 25,
              ),
              onPressed: () {
                Get.back();
              },
            ),
            shape:  CircleBorder(),
          ),
        ),
        title: Text(
          "تسجيل حساب جديد",
          style: TextStyle(color: AppColors.primaryColor),
        ),
      ),
      body: Builder(
        builder: (context) => Container(
          margin: EdgeInsets.all(12),
          child: SingleChildScrollView(
            child: Container(
              child: Obx(
                () => Column(
                  children: <Widget>[
                        FormBuilder(
                          // context,
                          key: controller.registerFbKey,
                          // autovalidate: true,
                          child: controller.userType.value == Config.Driver
                              ? Text("User one")
                              : Text("User Two") ,
                        ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

}

Login Page
class LoginPage extends GetView<LoginController> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: AppColors.whiteColor,
        elevation: 0,
        bottomOpacity: 0.0,
      ),
      body:  Container(
        child: SingleChildScrollView(
          child: Container(
            alignment: Alignment.center,
            margin: EdgeInsets.all(20),
            child: Column(
              children: [
                Align(
                  alignment: Alignment.topRight,
                  child: Text("This is Login Page"),
                ),
                _buildRegisterButton("Go to  SignUp Page"),

              ],
            ),
          ),
        ),
      ),
    );
  }


  Container _buildRegisterButton(text) {
    return Container(
      alignment: Alignment.center,
      child: ElevatedButton(
        style: ElevatedButton.styleFrom(
            primary: AppColors.buttonBackgroundColor,
            padding: EdgeInsets.symmetric(horizontal: 85, vertical: 10),
            shape:RoundedRectangleBorder(borderRadius: BorderRadius.circular(50))),
            child: Text(text, style: AppStyles.bigButtonTextStyle),
        onPressed: ()  {
          Get.toNamed(AppRoutes.RegisterPageURL);
        },
      ),
    );
  }


}
```

**Comment by eduardoflorence** [comment]
There is an error here:
`binding: BindingsBuilder(() => Get.lazyPut(() => RegisterPage())),`
The correct is:
`binding: BindingsBuilder(() => Get.lazyPut(() => RegisterController())),`
