### ISSUE TITLE
No constructor 'GetMaterialApp.' with matching arguments declared in class 'GetMaterialApp'

### ISSUE THREAD

**Issue by moxun33** [jonataslaw/getx#1302]
># When building a windows application, hot reload error is reported after modifying the code.

-   related [flutter_use#2](https://github.com/CNAD666/flutter_use/issues/2)

-  flutter version `Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)`

```js

======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building MyApp(dirty):
No constructor 'GetMaterialApp.' with matching arguments declared in class 'GetMaterialApp'.
Receiver: GetMaterialApp
Tried calling: new GetMaterialApp.()
Found: new GetMaterialApp.({Key? key, GlobalKey<NavigatorState>? navigatorKey, Widget? home, Map<String, (BuildContext) => Widget> routes, String? initialRoute, ((RouteSettings) => Route<dynamic>?)? onGenerateRoute, ((String) => List<Route<dynamic>>)? onGenerateInitialRoutes, ((RouteSettings) => Route<dynamic>?)? onUnknownRoute, List<NavigatorObserver> navigatorObservers, ((BuildContext, Widget?) => Widget)? builder, TextDirection? textDirection, String title, ((BuildContext) => String)? onGenerateTitle, Color? color, ThemeData? theme, ThemeData? darkTheme, ThemeMode themeMode, Locale? locale, Locale? fallbackLocale, Iterable<LocalizationsDelegate<dynamic>>? localizationsDelegates, ((List<Locale>?, Iterable<Locale>) => Locale?)? localeListResolutionCallback, ((Locale?, Iterable<Locale>) => Locale?)? localeResolutionCallback, Iterable<Locale> supportedLocales, bool debugShowMaterialGrid, bool showPerformanceOverlay, bool checkerboardRasterCacheImages, bool checkerboardOffscreenLayers, bool showSemanticsDebugger, bool debugShowCheckedModeBanner, Map<LogicalKeySet, Intent>? shortcuts, CustomTransition? customTransition, Map<String, Map<String, String>>? translationsKeys, Translations? translations, (() => void)? onInit, (() => void)? onReady, (() => void)? onDispose, ((Routing?) => void)? routingCallback, Transition? defaultTransition, List<GetPage<dynamic>>? getPages, bool? opaqueRoute, bool? enableLog, ((String, {bool isError}) => void)? logWriterCallback, bool? popGesture, Duration? transitionDuration, bool? defaultGlobalState, SmartManagement smartManagement, Bindings? initialBinding, GetPage<dynamic>? unknownRoute, ThemeData? highContrastTheme, ThemeData? highContrastDarkTheme, Map<Type, Action<Intent>>? actions}) => GetMaterialApp

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
When the exception was thrown, this was the stack: 
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:212:5)
#1      MyApp.build (package:flutter_use/main.dart)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
...
====================================================================================================
```

**Comment by jonataslaw** [comment]
Remove the dot after GetMaterialApp

`Found: new GetMaterialApp.({Key? key, GlobalKey<NavigatorState>? `

it would be Found: new GetMaterialApp({Key? key, GlobalKey<NavigatorState>?

**Comment by moxun33** [comment]
My code as belows, no any dot after GetMaterialApp. Weird!
```js

class MyApp extends StatelessWidget {
  // This module.main_get.widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'GetX on Windows',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.pink,
      ),
      navigatorKey: Get.key,
      initialRoute: RouteConfig.main,
      getPages: RouteConfig.getPages,
      defaultTransition: Transition.fade,
    );
  }
}
```
