### ISSUE TITLE
[ERROR]⛔️  Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by ufukhawk** [jonataslaw/getx#1435]
With get.off, I am preventing the splash screen page from going back.
```
Get.off (() => LoginScreen ());
```
After coming to the LoginScreen page;
  ```
Get.to (() => PhoneOTPScreen ());
```
If you want to switch to the PhoneOTPScreen page, I get the following error.

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building PhoneOTPScreenBody(dirty, state: _PhoneOTPScreenBodyState#4bfae):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  PhoneOTPScreenBody file:///Users/xxxx/Desktop/xxxx/xxxx/lib/screens/phone_otp/phone_otp_screen.dart:9:14
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3864:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3878:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3893:12)
#3      Localizations.of (package:flutter/src/widgets/localizations.dart:472:48)
#4      ApplicationLocalizations.of (xxxx/utils/locale/app_localization.dart:14:26)
```

main dart : 

```void main() {
  runApp(MainApp());
}

class MainApp extends StatefulWidget with WidgetsBindingObserver {
  @override
  _MainAppState createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    return GetMaterialApp(
      navigatorKey: Get.key,
      enableLog: true,
      defaultTransition: Transition.fade,
      opaqueRoute: Get.isOpaqueRouteDefault,
      popGesture: Get.isPopGestureEnable,
      transitionDuration: Get.defaultTransitionDuration,
      defaultGlobalState: Get.defaultOpaqueRoute,
      debugShowCheckedModeBanner: false,
      logWriterCallback: localLogWriter,
      theme: theme(),
      home: SplashScreen(),
      supportedLocales: [
        Locale('en', 'US'),
      ],
      locale: Utils.appLocale,
      localizationsDelegates: [
        const AppLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate
      ],
    );
  }

  void localLogWriter(String text, {bool isError = false}) {
    print("Log : " + text);
  }
}
```

**Comment by ufukhawk** [comment]
My advice to Flutter developers is never build your project based on 3rd party (and unrelated) libraries.

**Comment by jonataslaw** [comment]
Initially, follow the issue opening form. Without a replay code, it is not possible to analyze a possible problem.
Furthermore, it is not possible to verify any problem with a code snippet where you have:
SplashScreen> Get.off> Get.to
Furthermore, the error is clearly not related to this library. You are trying to access a state of a disabled StatefulWidget after the widget leaves the tree.
