### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by larryluo123** [jonataslaw/getx#1463]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
import 'dart:convert';
import 'package:get/get.dart';
import 'package:shike/common/api/api.dart';

class BaseProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.baseUrl = API.DOMAIN;

    //
    httpClient.addRequestModifier<void>((request) async {
      var stream = request.bodyBytes;  //
      var requestParams =
          await stream.transform(utf8.decoder).transform(LineSplitter()).toList();
      print("requestParams 002 ${requestParams}");

      return request;
    });

    httpClient.addResponseModifier((request, response) {
      return response;
    });
  }
}

```

**To Reproduce**
when add addRequestModifier, and get **request.bodyBytes** 
error :
`E/flutter (22690): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter (22690): #0      _GeneratedStreamImpl._createSubscription (dart:async/stream_impl.dart:505:18)
E/flutter (22690): #1      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter (22690): #2      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
E/flutter (22690): #3      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
E/flutter (22690): #4      _AsBroadcastStream.listen (dart:async/stream_impl.dart:824:31)
E/flutter (22690): #5      _HttpOutgoing.addStream (dart:_http/http_impl.dart:1555:22)
E/flutter (22690): #6      _StreamSinkImpl.addStream.targetAddStream (dart:_http/http_impl.dart:652:22)
E/flutter (22690): #7      _StreamSinkImpl.addStream (dart:_http/http_impl.dart:658:51)
E/flutter (22690): #8      _HttpOutboundMessage.addStream (dart:_http/http_impl.dart:871:20)
E/flutter (22690): #9      Stream.pipe (dart:async/stream.dart:698:27)
E/flutter (22690): #10     HttpRequestImpl.send (package:get/get_connect/http/src/http/io/http_request_io.dart:46:35)
E/flutter (22690): <asynchronous suspension>
E/flutter (22690): #11     GetHttpClient._performRequest (package:get/get_connect/http/src/http.dart:197:22)
E/flutter (22690): <asynchronous suspension>
E/flutter (22690): #12     GetHttpClient.post (package:get/get_connect/http/src/http.dart:344:22)
E/flutter (22690): <asynchronous suspension>
`

**Expected behavior**

**Screenshots**

**Flutter Version:**
Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale
    en-CN)

**Getx Version:**
  get: ^4.1.4

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
`  var stream = request.bodyBytes?.asBroadcastStream(); `

**Comment by geekcarl** [comment]
i have same problem ;
request.bodyBytes is build from `Stream.fromIterable,` that is single-subscription stream, 
if call `request.bodyBytes?.asBroadcastStream()` ，that means single-subscription  has been listen, 
so when call above before send request , it will throw this exception。
