### ISSUE TITLE
Cannot decode server response to json Flutter

### ISSUE THREAD

**Issue by khangahs** [jonataslaw/getx#1498]
**Describe the bug**
I'm trying to send a nested object to the server with GetConnect. However, after many attempts I fail to do so. I look onto Flutter Docs; nevertheless, it use the same JSON.decode as I am. The content type I set up for the backend is application/json. How I can solve this? When I'm sending the POST request, the console shows this message:

```
[GETX] Cannot decode server response to json
```

**Reproduction code
```dart
Future<List<MainItem>> addItem() async {
    var mainItem = MainItem(
      name: name,
      description: description,
      itemTypeId: itemTypeId,
      userId: userId,
      itemUuid: itemUuid,
      inventory: Inventory(
          inventoryUuid: '',
          price: 0,
          quantity: 0,
          box: 0,
          pricePerItem: 0,
          itemInBox: 0,
          inStoragePrice: 0,
          inStorageItem: 0),
      image: ItemImage(imageUrl: imageUrl),
      location: InventoryLocation(
          description: locationDescription,
          name: locationName,
          address: Address(
              countryId: countryId,
              stateId: stateId,
              streetAddress: streetAddress,
              city: city,
              zipCode: zipCode)),
    ).toJson();
    print('Values pass to Future: $mainItem', contentType: 'application/json; charset=UTF-8');
    final res = await post('/item/$userId', mainItem);
    if (res.status.hasError) {
      return Future.error(res.statusText!);
    } else {
//I think this shouldn't be decoded since content type is application/json
      return (res.body as List).map((e) => MainItem.fromJson(e)).toList();
    }
  }
```
If I run Chrome for debug, without hot reload, this shows up:
```
Expected a value of type 'List<MainItem>?', but got one of type 'TypeErrorImpl'
 at Object.throw_ [as throw] (http://localhost:60831/dart_sdk.js:5037:11)
    at Object.castError (http://localhost:60831/dart_sdk.js:5010:15)
    at Object.cast [as as] (http://localhost:60831/dart_sdk.js:5319:17)
    at dart.NullableType.new.as (http://localhost:60831/dart_sdk.js:6826:60)
    at http://localhost:60831/packages/booking_management_dashboard/screen/pages/tablet/widgets/choice_chip/choice_chip.dart.lib.js:6436:49
    at _RootZone.runUnary (http://localhost:60831/dart_sdk.js:37245:59)
    at _FutureListener.then.handleError (http://localhost:60831/dart_sdk.js:32513:48)
    at handleError (http://localhost:60831/dart_sdk.js:33044:51)
    at Function._propagateToListeners (http://localhost:60831/dart_sdk.js:33070:17)
    at _Future.new.[_completeWithValue] (http://localhost:60831/dart_sdk.js:32914:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60831/dart_sdk.js:32935:35)
    at Object._microtaskLoop (http://localhost:60831/dart_sdk.js:37497:13)
    at _startMicrotaskLoop (http://localhost:60831/dart_sdk.js:37503:13)
    at http://localhost:60831/dart_sdk.js:33274:9
```
Model:

```dart
class MainItem {
  String? name, description, userId, itemUuid, createdAt;
  int? id, itemTypeId;
  InventoryLocation? location;
  ItemImage? image;
  Inventory? inventory;

  MainItem({
    @required this.name,
    @required this.description,
    @required this.location,
    this.itemUuid,
    this.createdAt,
    this.userId,
    this.id,
    this.itemTypeId,
    this.image,
    this.inventory,
  });

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['id'] = id;
    data['uuid'] = itemUuid;
    data['user_id'] = userId;
    data['createdAt'] = createdAt;
    data['description'] = description;
    data['item_type_id'] = itemTypeId;
    data['location'] = location!.toJson();
    data['item_image'] = image!.toJson();
    data['inventory'] = inventory!.toJson();

    return data;
  }

  factory MainItem.fromJson(Map<String, dynamic> json) => MainItem(
        id: json['id'] as int? ?? 0,
        itemTypeId: json['item_type_id'] as int? ?? 0,
        name: json['name'] ?? 'Nothing found',
        itemUuid: json['uuid'] ?? 'Nothing found',
        userId: json['user_id'] ?? 'Nothing found',
        createdAt: json['createdAt'] ?? 'Nothing found',
        description: json['description'] ?? 'Nothing found',
        image: ItemImage.fromJson(json['item_image']),
        location: InventoryLocation.fromJson(json['location']),
        inventory: Inventory.fromJson(json['inventory']),
      );

  factory MainItem.fromRawJson(String str) =>
      MainItem.fromJson(json.decode(str));

  String toRawJson() => json.encode(toJson());

  @override
  String toString() {
    return 'Values are name: $name, description: $description, location : $location, userId: $userId,  image: $image';
  }
}
```
**Expected behavior**

GetX stop giving error

**Flutter Version:**
Enter the version of the Flutter you are using

**Getx Version:**
Latest

**Describe on which device you found the bug:**
Flutter Web

**Minimal reproduce code**
I tried print(res.bodyString), but it fail to print. Video to reproduce : https://drive.google.com/file/d/1UdZ7WJ8IJ69kfoNSE6sIXey-m6pDCJff/view

**Comment by khangahs** [comment]
After reading the docs carefully, it should be ```Future<Response>``` not ```Future<List<MainItem>>```. I tried to post my answer on StackOverflow; but, it blocks me. So, good luck :)
