### ISSUE TITLE
GetStream.notifyError - Null check operator used on a null value

### ISSUE THREAD

**Issue by psycura** [jonataslaw/getx#1567]
**Describe the bug**
When i try to use 
`someState.addError(someError)`

I receive an error:
```
flutter: UNDETECTED ERROR:Null check operator used on a null value
flutter: StackTrace:#0      GetStream._notifyError (package:get/get_rx/src/rx_stream/get_stream.dart:67:31)
#1      GetStream.addError (package:get/get_rx/src/rx_stream/get_stream.dart:106:5)
#2      _RxImpl.addError (package:get/get_rx/src/rx_types/rx_core/rx_impl.dart:181:13)
#3      OnboardCtr.setOnboardErrorState 
```

**Reproduction code
For example i have within some controller:
```
  final _onboardState = OnboardState.initial.obs;

  OnboardState get onboardState => _onboardState.value;

  Stream<OnboardState?> get onboardStateStream => _onboardState.stream;

  void setOnboardState(OnboardState value) {
    _onboardState.value = value;
  }

  void setOnboardErrorState(OnboardError error) {
    _onboardState.addError(error);
  }
```

And then in the widget i make subscription to the stream:

```
  final OnboardCtr _onbCtr = OnboardCtr.to;

  Future<void> register(String code) async {
    _onbCtr.setOnboardState(OnboardState.initial);
    await _sub?.cancel();
    _sub = _onbCtr.onboardStateStream.listen(
      _stateUpdateHandler,
      cancelOnError: true,
    );

    _sub!.onError(_onError);
    _onbCtr.registerPatient(code);
  }
```

**Expected behavior**
The onError handler should receive an error

I found a temporary solution.
In the `get_stream.dart`
In the `_notifyError` method

Change condition `if (item.cancelOnError!)`
to `if (item.cancelOnError??false)`
This solve the issue.

**Flutter Version:**
2.2.2

**Getx Version:**
4.1.4

Thanks

**Comment by jonataslaw** [comment]
Thanks! Fixing it now
