### ISSUE TITLE
in routingCallback use Get.snackbar have errors

### ISSUE THREAD

**Issue by inits** [jonataslaw/getx#1577]
- detail error is below
```

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4564 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4564:12)
#3      NavigatorState.push (package:flutter/src/widgets/navigator.dart:4480:5)
#4      ExtensionSnackbar.showSnackbar (package:get/get_navigation/src/extension_navigation.dart:102:30)
#5      ExtensionSnackbar.snackbar (package:get/get_navigation/src/extension_navigation.dart:198:7)
#6      MyApp.build.<anonymous closure> (package:ft_velocity/main.dart:45:15)
#7      GetObserver.didPush (package:get/get_navigation/src/routes/observers/route_observer.dart:125:15)
#8      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:3293:14)
#9      List.forEach (dart:core-patch/growable_array.dart:403:8)
#10     NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:4080:27)
#11     NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4036:5)
#12     NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4573:5)
#13     NavigatorState.push (package:flutter/src/widgets/navigator.dart:4480:5)
#14     NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:4212:12)
#15     GetNavigation.toNamed (package:get/get_navigation/src/extension_navigation.dart:565:37)
#16     Second.build.<anonymous closure> (package:ft_velocity/main.dart:171:17)
#17     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#18     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#19     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#20     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#21     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#22     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#23     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#24     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
#25     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#26     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
#27     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
#28     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#29     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#30     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#31     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#32     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#33     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#34     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#35     _rootRunUnary (dart:async/zone.dart:1370:13)
#36     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#38     _invoke1 (dart:ui/hooks.dart:182:10)
#39     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#40     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

```

- complete code is below

```
import 'package:flutter/material.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      defaultTransition: Transition.fadeIn, 
      getPages: [
        GetPage(
          name: '/',
          page: () => MyHomePage(),
        ),
        GetPage(
          name: '/first',
          page: () => First(),
        ),
        GetPage(
          name: '/second/:user',
          page: () => Second(),
        ),
        GetPage(
          name: '/third',
          page: () => Third(),
          transition: Transition.zoom,
        ),
      ],
      routingCallback: (routing) {
        print('跳转路由: ' + routing!.current);
        if (routing.current == '/third' && routing.isSnackbar == false) {
          print('safsss');
          Get.snackbar('title', 'message');
        }
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: VxAppBar(
        leading: Icon(Icons.backspace),
        title: 'hello'.tr.text.make(),
        searchBar: true,
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          40.heightBox,
          30.heightBox,
          ElevatedButton(
            onPressed: () {
              print(Get.isDarkMode);
              // 改变darkMode
              // Get.changeTheme(
              //   Get.isDarkMode ? ThemeData.light() : ThemeData.dark(),
              // );
              Get.snackbar('title', 'message');
            },
            child: Text('snackbar'),
          ),
          40.heightBox,
          ElevatedButton(
            onPressed: () {
              Get.toNamed('/first', arguments: 'Get is the bestest framework!');
            },
            child: Text('ToFirstPage'),
          ),
        ],
      ).scrollVertical(),
    );
  }
}

class FirstController extends GetxController {
  String dps = '';

  @override
  void onInit() {
    print('发送到first页面的数据');
    print(Get.arguments);
    this.dps = Get.arguments.toString();
    super.onInit();
  }
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // 注册FirstController();
    Get.put(FirstController());
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.add),
          onPressed: () {
            Get.snackbar("hi", "i am a modern snackbar");
          },
        ),
        title: Text('First Route'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Open route'),
          onPressed: () {
            Get.toNamed("/second/qiaos-paramsr?device=phone&id=354&name=Enzo");
          },
        ),
      ),
    );
  }
}

class SecondController extends GetxController {
  @override
  void onInit() {
    print('发送到second页面的动态网页链接数据');
    print(Get.parameters['device']);
    print(Get.parameters['id']);
    print(Get.parameters['name']);

    print('接受NamedParameters');
    print(Get.parameters['user']);
    super.onInit();
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.put(SecondController());
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.add),
          onPressed: () {
            Get.snackbar("hi", "i am a modern snackbar");
          },
        ),
        title: Text('second Route'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Open route'),
          onPressed: () {
            Get.toNamed("/third");
          },
        ),
      ),
    );
  }
}

class Third extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Third Route"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Get.back();
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}

```

**Comment by theowenyoung** [comment]
Same here

**Comment by jonataslaw** [comment]
routingCallback no more track snackbar's events on latest version
