### ISSUE TITLE
Unhandled Exception: Concurrent modification during iteration, Get.DeleteAll

### ISSUE THREAD

**Issue by msxenon** [jonataslaw/getx#1756]
**Describe the bug**
----I'm getting this error below when trying to reset the app Dependenceies after user log-out

[   +2 ms] E/flutter (12146): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Concurrent modification during iteration: _LinkedHashMap len:16.
[        ] E/flutter (12146): #0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:473:7)
[        ] E/flutter (12146): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:395:15)
[        ] E/flutter (12146): #2      GetInstance.deleteAll (package:get/get_instance/src/get_instance.dart:412:12)
[        ] E/flutter (12146): #3      Inst.deleteAll (package:get/get_instance/src/extension_instance.dart:120:21)
[        ] E/flutter (12146): #4      TrakAppDI.onReset (package:mobileapp/trak_app_di.dart:38:9)
**Reproduction code
 Get.deleteAll();

 

**To Reproduce**
1. put some services
2. Get.deleteAll() or await Get.deleteAll()
3. See error

**Expected behavior**
to clear all services and controllers

**Screenshots**

**Flutter Version:**
2.2.3
**Getx Version:**
4.3.6

**Describe on which device you found the bug:**
any

**Comment by armaniv11** [comment]
Facing same Issue, any solution
