### ISSUE TITLE
Run code of example_nav2, When I click the icon in the navbar quickly, it returns errors

### ISSUE THREAD

**Issue by xukecheng** [jonataslaw/getx#1919]
**Describe the bug**
I found this [example](https://github.com/jonataslaw/getx/tree/master/example_nav2) code has a bug： when I click the icon in the tabbar quickly, it returns errors.
this is video: https://imgur.com/a/Bjf45W7
message:
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterActivityAndFragmentDelegate(12431): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:51816/sby8LacQ-U8=/ws
[GETX] GetDelegate is created !
[GETX] GetInformationParser is created !
[GETX] Instance "AuthService" has been created
[GETX] Instance "AuthService" has been initialized
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
I/flutter (12431): GetInformationParser: route location: /
[GETX] GOING TO ROUTE /
[GETX] Instance "DashboardController" has been created
[GETX] Instance "DashboardController" has been initialized
[GETX] Redirect to null
[GETX] "DashboardController" onDelete() called
[GETX] "DashboardController" deleted from memory
[GETX] Redirect to null
[GETX] Instance "DashboardController" has been created
[GETX] Instance "DashboardController" has been initialized
[GETX] Redirect to null
[GETX] "DashboardController" onDelete() called
[GETX] "DashboardController" deleted from memory

════════ Exception caught by widgets library ═══════════════════════════════════
The following message was thrown building Obx(has builder, dirty, state: _ObxState#afdec):
"DashboardController" not found. You need to call "Get.put(DashboardController())" or "Get.lazyPut(()=>DashboardController())"

The relevant error-causing widget was
Obx
When the exception was thrown, this was the stack
#0      GetInstance.find
#1      GetView.controller
#2      DashboardView.build.<anonymous closure>
#3      Obx.build
#4      RxInterface.notifyChildren
#5      _ObxState.build
#6      StatefulElement.build
#7      ComponentElement.performRebuild
#8      StatefulElement.performRebuild
#9      Element.rebuild
#10     BuildOwner.buildScope
#11     WidgetsBinding.drawFrame
#12     RendererBinding._handlePersistentFrameCallback
#13     SchedulerBinding._invokeFrameCallback
#14     SchedulerBinding.handleDrawFrame
#15     SchedulerBinding._handleDrawFrame
#19     _invoke (dart:ui/hooks.dart:166:10)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#21     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
"DashboardController" not found. You need to call "Get.put(DashboardController())" or "Get.lazyPut(()=>DashboardController())"
The relevant error-causing widget was
Obx
════════════════════════════════════════════════════════════════════════════════
```

I wrote similar code For my own project, and repeat click action, then it returns errors:
```
Restarted application in 4,519ms.
[GETX] GetDelegate is created !
[GETX] GetInformationParser is created !
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
I/flutter (12617): GetInformationParser: route location: /
[GETX] GOING TO ROUTE /
[GETX] Instance "HomeController" has been created
[GETX] Instance "HomeController" has been initialized

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building GetRouterOutlet(state: _RouterOutletState<GetDelegate, GetNavConfig>#23340):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3818 pos 14: '!pageKeyToOldEntry.containsKey(page.key)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
GetRouterOutlet
When the exception was thrown, this was the stack
#2      NavigatorState._updatePages
#3      NavigatorState.didUpdateWidget
#4      StatefulElement.update
#5      Element.updateChild
#6      ComponentElement.performRebuild
#7      StatefulElement.performRebuild
#8      Element.rebuild
#9      StatefulElement.update
#10     Element.updateChild
#11     ComponentElement.performRebuild
#12     Element.rebuild
#13     StatelessElement.update
#14     Element.updateChild
#15     ComponentElement.performRebuild
#16     Element.rebuild
#17     ProxyElement.update
#18     Element.updateChild
#19     ComponentElement.performRebuild
#20     Element.rebuild
#21     ProxyElement.update
#22     Element.updateChild
#23     RenderObjectElement.updateChildren
#24     MultiChildRenderObjectElement.update
#25     Element.updateChild
#26     ComponentElement.performRebuild
#27     StatefulElement.performRebuild
#28     Element.rebuild
#29     StatefulElement.update
#30     Element.updateChild
#31     ComponentElement.performRebuild
#32     Element.rebuild
#33     ProxyElement.update
#34     Element.updateChild
#35     ComponentElement.performRebuild
#36     StatefulElement.performRebuild
#37     Element.rebuild
#38     StatefulElement.update
#39     Element.updateChild
#40     SingleChildRenderObjectElement.update
#41     Element.updateChild
#42     ComponentElement.performRebuild
#43     Element.rebuild
#44     StatelessElement.update
#45     Element.updateChild
#46     SingleChildRenderObjectElement.update
#47     Element.updateChild
#48     ComponentElement.performRebuild
#49     StatefulElement.performRebuild
#50     Element.rebuild
#51     StatefulElement.update
#52     Element.updateChild
#53     ComponentElement.performRebuild
#54     StatefulElement.performRebuild
#55     Element.rebuild
#56     StatefulElement.update
#57     Element.updateChild
#58     ComponentElement.performRebuild
#59     Element.rebuild
#60     ProxyElement.update
#61     Element.updateChild
#62     ComponentElement.performRebuild
#63     Element.rebuild
#64     StatelessElement.update
#65     Element.updateChild
#66     ComponentElement.performRebuild
#67     StatefulElement.performRebuild
#68     Element.rebuild
#69     StatefulElement.update
#70     Element.updateChild
#71     ComponentElement.performRebuild
#72     Element.rebuild
#73     ProxyElement.update
#74     Element.updateChild
#75     ComponentElement.performRebuild
#76     StatefulElement.performRebuild
#77     Element.rebuild
#78     StatefulElement.update
#79     Element.updateChild
#80     ComponentElement.performRebuild
#81     StatefulElement.performRebuild
#82     Element.rebuild
#83     BuildOwner.buildScope
#84     WidgetsBinding.drawFrame
#85     RendererBinding._handlePersistentFrameCallback
#86     SchedulerBinding._invokeFrameCallback
#87     SchedulerBinding.handleDrawFrame
#88     SchedulerBinding._handleDrawFrame
#92     _invoke (dart:ui/hooks.dart:166:10)
#93     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#94     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════
E/flutter (12617): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3955 pos 12: '_debugLocked && !_debugUpdatingPage': is not true.
E/flutter (12617): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (12617): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (12617): #2      NavigatorState._flushHistoryUpdates
E/flutter (12617): #3      _RouteEntry.handlePush.<anonymous closure>
E/flutter (12617): #4      TickerFuture.whenCompleteOrCancel.thunk
E/flutter (12617): #5      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (12617): #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (12617): <asynchronous suspension>
E/flutter (12617): #7      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart)
E/flutter (12617): <asynchronous suspension>
E/flutter (12617):

════════ Exception caught by widgets library ═══════════════════════════════════
A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was
GetRouterOutlet
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════
```

**My Code:**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../routes/app_pages.dart';
import '../controllers/home_controller.dart';

class HomeView extends GetView<HomeController> {
  @override
  Widget build(BuildContext context) {
    return GetRouterOutlet.builder(
      builder: (context, delegate, currentRoute) {
        final HomeController controller = Get.find<HomeController>();

        return Scaffold(
          body: GetRouterOutlet(
            initialRoute: Routes.UNREAD_LIST,
            // anchorRoute: Routes.HOME,
            key: Get.nestedKey(Routes.HOME),
          ),
          bottomNavigationBar: Obx(
            () => BottomNavigationBar(
              currentIndex: controller.currentIndex,
              onTap: (value) {
                switch (value) {
                  case 0:
                    controller.currentIndex = 0;
                    delegate.toNamed(Routes.UNREAD_LIST);
                    break;
                  case 1:
                    controller.currentIndex = 1;
                    delegate.toNamed(Routes.SEARCH);
                    break;
                  default:
                }
              },
              items: [
                BottomNavigationBarItem(
                  icon: Icon(Icons.home),
                  label: 'Home',
                ),
                BottomNavigationBarItem(
                  icon: Icon(Icons.account_box_rounded),
                  label: 'Profile',
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}

```

**Flutter Version:**
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (12 days ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3

**Getx Version:**
4.3.8

**Comment by ahmednfwela** [comment]
this is broken because of https://github.com/jonataslaw/getx/pull/1894
