### ISSUE TITLE
Run Example broken

### ISSUE THREAD

**Issue by taosimple** [jonataslaw/getx#2001]
**Describe the bug**
Just clone getx and Run example broked:
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
Navigator.onGenerateRoute returned null when requested to build route "/".

The onGenerateRoute callback must never return null, unless an onUnknownRoute callback is provided as well.
The Navigator was: NavigatorState#94170(lifecycle state: initialized)
  lifecycle state: initialized
The relevant error-causing widget was: 
  Directionality Directionality:file:///Users/taotao/Documents/repo/getx/lib/get_navigation/src/root/get_material_app.dart:217:12
When the exception was thrown, this was the stack: 
#0      NavigatorState._routeNamed.<anonymous closure> (package:flutter/src/widgets/navigator.dart:4190:11)
#1      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:4200:8)
#2      Navigator.defaultGenerateInitialRoutes (package:flutter/src/widgets/navigator.dart:2856:28)
#3      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3454:41)
#4      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:984:5)
#5      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:970:7)
#6      NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3500:11)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4826:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3422:20)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#27     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#28     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#30     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#31     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

```

**Flutter Env:**
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/taotao/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 week ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by ahmednfwela** [comment]
use my branch instead for now : https://github.com/Bdaya-Dev/getx
