### ISSUE TITLE
Get.dialog will be error  if I invoke on the SuperController's onInit()  method

### ISSUE THREAD

**Issue by WinWang** [jonataslaw/getx#2062]
class HomeController extends BaseController<TestApi> {
  
  @override
  void onInit() {
    super.onInit();
    loadNet();
    **_Get.showLoading();_**
  }

/// @description :get 扩展函数
extension GetExtension on GetInterface {
  ///隐藏dialog
  dismiss() {
    if (Get.isDialogOpen != null && Get.isDialogOpen!) {
      Get.back();
    }
  }

  ///显示dialog
  showLoading({String text = ''}) {
    if (Get.isDialogOpen != null && Get.isDialogOpen!) {
      Get.back();
    }
    Get.dialog(LoadingDialog(text: text.isEmpty ? "加载中" : text),
        transitionDuration: const Duration(milliseconds: 500),
        barrierDismissible: false);
  }
}

***********************************************
Exception:
======== Exception caught by widgets library =======================================================
The following assertion was thrown building HomePage(dirty):
visitChildElements() called during build.

The BuildContext.visitChildElements() method can't be called during build because the child list is still being updated at that point, so the children might not be constructed yet, or might be old children that are going to be replaced.
The relevant error-causing widget was: 
  HomePage HomePage:file:///Users/wangchangsheng/Project/Flutter/WanAndroid_WinWang/lib/business/page/main/main_page.dart:15:21
When the exception was thrown, this was the stack: 
#0      Element.visitChildElements.<anonymous closure> (package:flutter/src/widgets/framework.dart:3277:7)
#1      Element.visitChildElements (package:flutter/src/widgets/framework.dart:3286:6)
#2      GetNavigation.overlayContext (package:get/get_navigation/src/extension_navigation.dart:1148:40)
#3      ExtensionDialog.generalDialog (package:get/get_navigation/src/extension_navigation.dart:128:22)
#4      ExtensionDialog.dialog (package:get/get_navigation/src/extension_navigation.dart:85:12)
#5      GetExtension.showLoading (package:flutter_wan_android/ext/get_extension.dart:18:9)
#6      BaseController.sendRequest (package:flutter_wan_android/base/base_controller.dart:32:11)
#7      HomeController.getBannerData (package:flutter_wan_android/business/page/home/home_page.dart:61:5)
#8      HomeController.loadNet (package:flutter_wan_android/business/page/home/home_page.dart:69:5)
#9      HomeController.onInit (package:flutter_wan_android/business/page/home/home_page.dart:51:5)
#10     GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66:5)
#11     InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12:26)
#12     GetInstance._startController (package:get/get_instance/src/get_instance.dart:253:16)
#13     GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:204:11)
#14     GetInstance.find (package:get/get_instance/src/get_instance.dart:301:17)
#15     GetView.controller (package:get/get_state_manager/src/simple/get_view.dart:38:37)
#16     BaseStatelessWidget.build (package:flutter_wan_android/base/base_stateless_widget.dart:18:13)
#17     StatelessElement.build (package:flutter/src/widgets/framework.dart:4662:28)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#23     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (19 frames)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#44     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#45     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (93 frames)
#138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#141    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#143    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#144    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#145    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)

![image](https://user-images.githubusercontent.com/19348069/146557451-9d1ec7d3-a82b-40ab-8f6f-32d0ddf8575b.png)

**Comment by jonataslaw** [comment]
You need call dialog on onReady rather onInit

**Comment by pouriajava** [comment]
**Thanks to** **@jonataslaw** 
I share my **example** code : 

class BaseDashBoardController extends GetxController {
  RxBool toggleStatus = false.obs;
  @override
  void onInit() {
    super.onInit();
    toggleStatus.listen((bool b) {
      toggleStatus.value = b;
      update();
    });
  }
  @override
  void onReady() {
    super.onReady();
    ExampleDialog.show();
  }
}

class ExampleDialog{
  static Future show() async{
    return Get.defaultDialog(
      title: "Dialog Title",
      middleText: "Hello world!",
      backgroundColor: Colors.green,
      titleStyle: TextStyle(color: Colors.white),
      middleTextStyle: TextStyle(color: Colors.white),
    );
  }
}
