### ISSUE TITLE
Get.defaultDialog throws exceptions if used with snackbar

### ISSUE THREAD

**Issue by grobokop** [jonataslaw/getx#2196]
**Describe the bug**
Trying to use get.defaultDialog after displaying snackbar cause issues if snackbar is not fully dissapear.

**Reproduction code

example:

```dart

void main() {
  runApp(const GetMaterialApp(home:MyHomePage()));
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void doFail() {throw Exception('i am failing');}
  void press() {
    Get.closeAllSnackbars();
    Get.defaultDialog(onConfirm: () {
      //Get.back();
      Get.close(1);
      try {
        doFail();
      }
      catch (e){
        Get.snackbar("Title","something wrong",snackPosition: SnackPosition.BOTTOM,isDismissible: false, onTap: (snack) {
            Get.back();
          },
          duration: null,
        );
      }
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child:ElevatedButton(onPressed: press, child: Text("Press"))),
    );
  }
}

```

**To Reproduce**
1. Press 'press' button
2. On dialog press 'Ok' button
3. press button 'press' again. And press the 'oK' on dialog BEFORE snackbar dissapear (may requier to do more then one time)
4. Snackbar is not dissapear any more and following error appear at logs:

```
E/flutter (14432): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field '_controller@82359576' has not been initialized.
E/flutter (14432): #0      SnackbarController._controller (package:get/get_navigation/src/snackbar/snackbar_controller.dart)
E/flutter (14432): #1      SnackbarController._removeEntry (package:get/get_navigation/src/snackbar/snackbar_controller.dart:314:7)
E/flutter (14432): #2      SnackbarController.close (package:get/get_navigation/src/snackbar/snackbar_controller.dart:55:5)
E/flutter (14432): #3      _SnackBarQueue._cancelAllJobs (package:get/get_navigation/src/snackbar/snackbar_controller.dart:363:29)
E/flutter (14432): #4      SnackbarController.cancelAllSnackbars (package:get/get_navigation/src/snackbar/snackbar_controller.dart:336:20)
E/flutter (14432): #5      GetNavigation.closeAllSnackbars (package:get/get_navigation/src/extension_navigation.dart:1120:24)
E/flutter (14432): #6      _MyHomePageState.press (package:reproduce/main.dart:19:9)
E/flutter (14432): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (14432): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (14432): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter (14432): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (14432): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (14432): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
E/flutter (14432): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)

```

**Expected behavior**
Snackbar is closed after snackbar click or dialog open

**Screenshots**

**Flutter Version:**
 2.8.1 

**Getx Version:**
4.6.1

**Describe on which device you found the bug:**
HUAWEI CAN-L11

**Minimal reproduce code**
Code provided

**Comment by maliksenpai** [comment]
```
void main() {
  runApp(const GetMaterialApp(home:MyHomePage()));
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void doFail() {throw Exception('i am failing');}
  void press() {
    Get.closeCurrentSnackbar();
    Get.defaultDialog(onConfirm: () {
      //Get.back();
      Get.close(1);
      try {
        doFail();
      }
      catch (e){
        Get.snackbar("Title","something wrong",snackPosition: SnackPosition.BOTTOM,isDismissible: false, onTap: (snack) {
          Get.back();
        },
          duration: null,
        );
      }
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child:ElevatedButton(onPressed: press, child: Text("Press"))),
    );
  }
}
```

I tested this code on WVGA API 30. I found there is a bug about async functions about snackbar i will look at this but this code work as you want. use `Get.closeCurrentSnackbar();`  instead of `Get.closeAllSnackbars();`

**Comment by grobokop** [comment]
Hi, did you click to button really fast to replicate the issue? (i.e. - you should not wait till animation of snackbar ends, need to click before). I tested and issue is also on different samsung devices.
I implement work-around to use always use only one snackbar and wait while it closed on then() callback.
But is not closeAllSnackbars intended to do what the function name suggest and close everything without making me worry about it?

**Comment by maliksenpai** [comment]
Yeah i tested really fast but its working with `Get.closeCurrentSnackbar();`. Yeah closeAllSnackbars must close all snackbars but i think there is a some bug about async. I will look at this.
