### ISSUE TITLE
Release build crashes on start

### ISSUE THREAD

**Issue by SebRut** [jonataslaw/getx#2206]
**Describe the bug**
Running the application in release builds, e.g. `flutter run --release`, crashes GetX on start with this stacktrace:

```
I/flutter (31203):       [Get] the improper use of a GetX has been detected. 
I/flutter (31203):       You should only use GetX or Obx for the specific widget that will be updated.
I/flutter (31203):       If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
I/flutter (31203):       or insert them outside the scope that GetX considers suitable for an update 
I/flutter (31203):       (example: GetX => HeavyWidget => variableObservable).
I/flutter (31203):       If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.
I/flutter (31203):       
I/flutter (31203): #0      RxInterface.notifyChildren (package:get/get_rx/src/rx_types/rx_core/rx_interface.dart:29)
I/flutter (31203): #1      _ObxState.build (package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart:54)
I/flutter (31203): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870)
I/flutter (31203): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754)
I/flutter (31203): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
I/flutter (31203): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
I/flutter (31203): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
I/flutter (31203): #11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
I/flutter (31203): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
I/flutter (31203): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
I/flutter (31203): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
I/flutter (31203): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
I/flutter (31203): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
I/flutter (31203): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
I/flutter (31203): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
I/flutter (31203): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
I/flutter (31203): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6284)
I/flutter (31203): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
I/flutter (31203): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919)
I/flutter (31203): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4477)
I/flutter (31203): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735)
I/flutter (31203): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729)
I/flutter (31203): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #94     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422)
I/flutter (31203): #95     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433)
I/flutter (31203): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790)
I/flutter (31203): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:3540)
I/flutter (31203): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780)
I/flutter (31203): #99     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928)
```

**Reproduction code
Private on GitLab, can add as guest if needed.

**To Reproduce**
1. Run app with `flutter run --release` on a android device

**Expected behavior**
The app runs like in debug builds.

**Flutter Version:**
2.10.2

**Getx Version:**
4.6.1

**Describe on which device you found the bug:**
Samsung Galaxy S20+

**Comment by SebRut** [comment]
I was able to isolate the issue to an `Obx` call:

View: 
```dart
class ArticlesPage extends GetView<ArticlesController> {
  @override
  Widget build(BuildContext context) {
    return Obx(() => ToggleButtons(
            children: [
              Icon(Icons.view_carousel_rounded),
              Icon(Icons.grid_view_rounded),
            ],
            onPressed: controller.onViewLayoutButtonPressed,
            isSelected: controller.selectedViewLayoutMatrix));
  }
}
```

ArticlesController (onInit etc. stripped):
```dart
class ArticlesController extends GetxController
    with StateMixin<List<ArticleModel>> {
  final selectedViewLayoutMatrix = [false, true].obs;

  void onViewLayoutButtonPressed(int index) {
    switch (index) {
      case 0:
        viewLayout.value = ViewLayout.carousel;
        selectedViewLayoutMatrix.value = [true, false];
        break;
      case 1:
        viewLayout.value = ViewLayout.list;
        selectedViewLayoutMatrix.value = [false, true];
        break;
    }
  }
}
```

**Comment by arjundevlucid** [comment]
````
class ArticlesPage extends GetView<ArticlesController> {
  @override
  Widget build(BuildContext context) {
    return Obx(() => ToggleButtons(
            children: [
              Icon(Icons.view_carousel_rounded),
              Icon(Icons.grid_view_rounded),
            ],
            onPressed: controller.onViewLayoutButtonPressed,
            isSelected: controller.selectedViewLayoutMatrix.value));
///use .value on obs variable
  }
}
````

**Comment by SebRut** [comment]
> ///use .value on obs variable

That gives me
`The member 'value' can only be used within instance members of subclasses of 'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart'.dart(invalid_use_of_protected_member)
`

and the problem persists.

**Comment by arjundevlucid** [comment]
can you try  .toList() ?

**Comment by SebRut** [comment]
> can you try .toList() ?

That seems to work, ty :)
