### ISSUE TITLE
Snackbar Failed Assertion

### ISSUE THREAD

**Issue by kgonyon** [jonataslaw/getx#2208]
**Describe the bug**
I am using `Get.snackbar(...)` and when it finishes disposing I keep getting the following error 
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:get[/get_navigation/src/snackbar/snackbar_controller.dart]()': Failed assertion: line 99 pos 12: '!_transitionCompleter.isCompleted': Cannot configure a snackbar after disposing it.
#0      _AssertionError._doThrowNew (dart:core-patch[/errors_patch.dart:51:61]())
#1      _AssertionError._throwNew (dart:core-patch[/errors_patch.dart:40:5]())
#2      SnackbarController._configureSnackBarDisplay 
#3      SnackbarController._configureOverlay 
#4      SnackbarController._show 
#5      GetQueue._check
#6      GetQueue._check
<asynchronous suspension>
```

**Reproduction code**

```dart
class _ErrorQueue {
  static late final instance = _ErrorQueue();

  late final _controller = StreamController<ControllerError>.broadcast();

  Stream<ControllerError> getStream() {
    return _controller.stream;
  }

  void reportError(ControllerError error) {
    _controller.add(error);
  }
}

class ControllerError<E> {
  final String message;
  final E? parent;
  ControllerError(this.message, {this.parent});
}

class ControllerErrorListener extends StatefulWidget {
  final Widget child;

  const ControllerErrorListener({Key? key, required this.child})
      : super(key: key);

  @override
  State<ControllerErrorListener> createState() =>
      _ControllerErrorListenerState();
}

class _ControllerErrorListenerState extends State<ControllerErrorListener> {
  StreamSubscription? subscription;

  @override
  void initState() {
    subscription = _ErrorQueue.instance.getStream().listen((error) {
      Get.snackbar(
        "Network Error",
        error.message,
        backgroundColor: Theme.of(context).errorColor,
        animationDuration: const Duration(milliseconds: 500),
      ).show();
    });
    super.initState();
  }

  @override
  void dispose() {
    subscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}

void main() async {
  runApp(const LOPTeamApp());
}


class LOPTeamApp extends StatelessWidget {
  const LOPTeamApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return _build(context);
  }

  Widget _build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: "/test",
      getPages: [
        GetPage(
          name: "/test",
          page: () => ControllerErrorListener(
            child: Center(
              child: TextButton(
                onPressed: () {
                  ErrorQueue.instance.reportError(
                    ControllerError("Testing Error"),
                  );
                },
                child: const Text("SnackBar"),
              ),
            ),
          ),
        )
      ],
      title: 'Flutter Demo',
      theme: lopTheme,
    );
  }
}
```

**To Reproduce**
1. Click Snackbar button
2. Wait for Snackbar to dismiss itself

**Expected behavior**
Snack bar should dismiss with no errors

**Flutter Version:**
Flutter 2.10.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fdd0af78bb (4 weeks ago) • 2022-01-25 22:01:33 -0600
Engine • revision 5ac30ef0c7
Tools • Dart 2.16.0 (build 2.16.0-134.5.beta) • DevTools 2.9.2

**Getx Version:**
^4.6.1

**Describe on which device you found the bug:**
IOS simulator
OSX Desktop
Web

**Comment by Nandan-Wewhare** [comment]
Any updates on this issue?

**Comment by Apollo108** [comment]
Same thing here. Waiting for updates.

**Comment by sametserpil** [comment]
Any updates on this?

**Comment by jonataslaw** [comment]
In fact, the show() method should not be invoked unless you have a custom widget that inherits from GetSnackbar.

Get.snackbar() does the job, as it is in the docs.
This is not a workaround, it is an official recommendation.
