### ISSUE TITLE
Obx causes assert: '_lifecycleState != _ElementLifecycle.defunct': is not true

### ISSUE THREAD

**Issue by agordeev** [jonataslaw/getx#2258]
**Describe the bug**

get-5.0.0-beta.36

When I use `Obx` on a different views that are being created and disposed, I get error:

```
flutter: 'package:flutter[/src/widgets/framework.dart]()': Failed assertion: line 4397 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
package:flutter/…/widgets/framework.dart:4397
flutter:
#0      _AssertionError._doThrowNew (dart:core-patch[/errors_patch.dart:51:61]())
#1      _AssertionError._throwNew (dart:core-patch[/errors_patch.dart:40:5]())
#2      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4397
#3      ObserverComponent._safeRebuild
package:get/…/simple/simple_builder.dart:115
```

Possibly related to https://github.com/jonataslaw/getx/issues/360

**Comment by jonataslaw** [comment]
Try the .50 beta, I think this has already been fixed.

**Comment by agordeev** [comment]
You're right, thanks!
