### ISSUE TITLE
The following _CastError was thrown building Directionality(textDirection: ltr): Null check operator used on a null value

### ISSUE THREAD

**Issue by ettaegbe** [jonataslaw/getx#2266]
Hello, I'm getting a this error when ever my app is trying to open a fire dynamic link generated by the app.
If I open another link let say a website the app works fine but once a user is redirected by firebase, the app crashes. 

I tried to pass TextDirection when starting my app but it doesn't still solve the problem. 

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Directionality(textDirection: ltr):
**'Null check operator used on a null value'**

The relevant error-causing widget was: 
  Directionality Directionality:file:///D:/projects/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/root/get_material_app.dart:328:12
When the exception was thrown, this was the stack: 
#0      PageRedirect.page (package:get/get_navigation/src/routes/route_middleware.dart:199:50)
#1      GetMaterialApp.initialRoutesGenerate (package:get/get_navigation/src/root/get_material_app.dart:348:9)
#2      _WidgetsAppState.build.<anonymous closure> (package:flutter/src/widgets/app.dart:1556:51)
#3      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3290:41)
#4      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:887:5)
#5      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:873:7)
#6      NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3336:11)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4914:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (331 frames)
#339    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#340    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#341    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#342    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#343    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#344    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#345    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#346    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#347    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

Please @jasonlaw can you check?

**Comment by robbymichael1** [comment]
did you find some solution for this?
