### ISSUE TITLE
GraphQL query works under debug mode, but not works under release mode

### ISSUE THREAD

**Issue by huahouye** [jonataslaw/getx#2282]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
import 'package:flutter/material.dart';

import 'package:get/get.dart';

void main() {
  runApp(
    GetMaterialApp(
      title: "Application",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
    ),
  );
}

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
}

class AppPages {
  AppPages._();

  static const INITIAL = Routes.HOME;

  static final routes = [
    GetPage(
      name: _Paths.HOME,
      page: () => HomeView(),
      binding: HomeBinding(),
    ),
  ];
}

class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<HomeController>(
      () => HomeController(),
    );
    Get.lazyPut<CountriesProvider>(
      () => CountriesProvider(),
    );
  }
}

class HomeView extends GetView<HomeController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('HomeView'),
          centerTitle: true,
        ),
        body: Column(
          children: [
            ElevatedButton(
                onPressed: () {
                  controller.loadRemoteData();
                },
                child: Text('load data')),
            Obx(
              (() => Center(
                    child: Text('${controller.responseData}'),
                  )),
            ),
          ],
        ));
  }
}

class HomeController extends GetxController {
  final CountriesProvider _settingProvider = Get.find();
  final responseData = ''.obs;

  loadRemoteData() async {
    var res = await _settingProvider.fetchData();
    responseData.value = res.isOk ? res.body.toString() : '';
    debugPrint(responseData.toString());
  }
}

class CountriesProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.baseUrl = 'https://countries.trevorblades.com/';
  }

  Future<GraphQLResponse<Map>> fetchData() {
    String queryString = r"""
      query test($cty: ID!){
        country(code: $cty) {
          name
          native
          capital
          emoji
          currency
          languages {
            code
            name
          }
        }
      }
      """;

    return query<Map>(queryString, url: "", variables: {"cty": "BR"});
  }
}

```

**To Reproduce**
1. `flutter run` under debug mode, click 'load data' button on screen, it can load graphql data from `https://countries.trevorblades.com/`
2. `flutter run --release` under release mode it does not work.

Excaption show as below:

```
Launching lib/main.dart on MI 6 in release mode...
Running Gradle task 'assembleRelease'...                           33.3s
✓  Built build/app/outputs/flutter-apk/app-release.apk (6.4MB).
Installing build/app/outputs/flutter-apk/app.apk...                 3.0s

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
E/flutter (23504): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (23504): Receiver: null
E/flutter (23504): Tried calling: []("errors")
E/flutter (23504): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
E/flutter (23504): #1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
E/flutter (23504): #2      GetConnect.query (package:get/get_connect/connect.dart:316)
E/flutter (23504): <asynchronous suspension>
E/flutter (23504): #3      HomeController.loadRemoteData (package:getx_graphql_bug/main.dart:81)
E/flutter (23504): <asynchronous suspension>
E/flutter (23504):
```

**Environment:**

```
get: 4.6.1
get-cli: 1.7.1
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-37-generic, locale en_US.UTF-8)
```

I find anthor issue [here #1093](https://github.com/jonataslaw/getx/issues/1093) , not sure if they are related.

**Comment by huahouye** [comment]
sorry, I forgot to include the following permissions in AndroidManifest.xml 

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
