### ISSUE TITLE
Getting Exception when trying close snackbar

### ISSUE THREAD

**Issue by fullflash** [jonataslaw/getx#2487]
Get.closeCurrentSnackbar();

```
+12246 ms] E/flutter ( 5276): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:get/get_navigation/src/snackbar/snackbar_controller.dart': Failed assertion: line 99 pos 12: '!_transitionCompleter.isCompleted': Cannot configure a snackbar after disposing it.
package:get/…/snackbar/snackbar_controller.dart:99
[        ] E/flutter ( 5276): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] E/flutter ( 5276): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] E/flutter ( 5276): #2      SnackbarController._configureSnackBarDisplay
package:get/…/snackbar/snackbar_controller.dart:99
[        ] E/flutter ( 5276): #3      SnackbarController._configureOverlay
package:get/…/snackbar/snackbar_controller.dart:95
[        ] E/flutter ( 5276): #4      SnackbarController._show
package:get/…/snackbar/snackbar_controller.dart:331
[        ] E/flutter ( 5276): #5      GetQueue._check
package:get/…/queue/get_queue.dart:42
[        ] E/flutter ( 5276): #6      GetQueue._check
package:get/…/queue/get_queue.dart:47
[        ] E/flutter ( 5276): <asynchronous suspension>
[        ] E/flutter ( 5276):
[ +391 ms] I/flutter ( 5276): evict tile: Coords(69727.0, 64115.0, 17.0) -> true
[        ] I/flutter ( 5276): evict tile: Coords(69726.0, 64114.0, 17.0) -> true
[        ] I/flutter ( 5276): evict tile: Coords(69727.0, 64114.0, 17.0) -> true
[        ] I/flutter ( 5276): evict tile: Coords(69728.0, 64114.0, 17.0) -> true
[        ] I/flutter ( 5276): evict tile: Coords(69726.0, 64115.0, 17.0) -> true
```

**Comment by JohnF17** [comment]
Have a look at my comment here #2208, it might help. ✌️
