### ISSUE TITLE
 Unhandled Exception: LateInitializationError: Field '_controller@1226359576' has not been initialized

### ISSUE THREAD

**Issue by jonex41** [jonataslaw/getx#2761]
i implemented a push notification, everything is working fine, when app is in foreground or background, but when app us terminated, and push notification is tapped to open the app, the navigation and snackbar, dialog stop showing throwing this error

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_controller@1226359576' has not been initialized.
                                                                                                    #0      SnackbarController._controller (package:get/get_navigation/src/snackbar/snackbar_controller.dart)
                                                                                                    #1      SnackbarController._removeEntry (package:get/get_navigation/src/snackbar/snackbar_controller.dart:314:7)
                                                                                                    #2      SnackbarController.close (package:get/get_navigation/src/snackbar/snackbar_controller.dart:55:5)
                                                                                                    #3      _SnackBarQueue._closeCurrentJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:370:29)
                                                                                                    #4      SnackbarController.closeCurrentSnackbar (package:get/get_navigation/src/snackbar/snackbar_controller.dart:340:26)
                                                                                                    #5      GetNavigation.closeCurrentSnackbar (package:get/get_navigation/src/extension_navigation.dart:1124:30)
                                                                                                    #6      hideLoader.<anonymous closure> (package:pick3d/src/utils/utils.dart:87:17)
                                                                                                    #7      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
                                                                                                    #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
                                                                                                    #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
                                                                                                    #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
                                                                                                    #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
2023-04-01 09:00:21.956  5958-6019  flutter                 com.app.pick3Di                      E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_controller@1226359576' has not been initialized.
                                                                                                    #0      SnackbarController._controller (package:get/get_navigation/src/snackbar/snackbar_controller.dart)
                                                                                                    #1      SnackbarController._removeEntry (package:get/get_navigation/src/snackbar/snackbar_controller.dart:314:7)
                                                                                                    #2      SnackbarController.close (package:get/get_navigation/src/snackbar/snackbar_controller.dart:55:5)
                                                                                                    #3      _SnackBarQueue._closeCurrentJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:370:29)
                                                                                                    #4      SnackbarController.closeCurrentSnackbar (package:get/get_navigation/src/snackbar/snackbar_controller.dart:340:26)
                                                                                                    #5      GetNavigation.closeCurrentSnackbar (package:get/get_navigation/src/extension_navigation.dart:1124:30)
                                                                                                    #6      showLoader.<anonymous closure> (package:pick3d/src/utils/utils.dart:64:17)
                                                                                                    #7      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
                                                                                                    #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
                                                                                                    #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
                                                                                                    #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
                                                                                                    #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

**Comment by longforus** [comment]
i have the same error

**Comment by longforus** [comment]
after run flutter hot reload,this error appeared

**Comment by tp-coderbabu** [comment]
facing the same error when a user does click multiple times for showing the snack bar.

`Future<void> showToast({
  required String title,
  String? subTitle,
}) async {
  if (Get.isSnackbarOpen) {
    await Get.closeCurrentSnackbar();
  }
  Get.snackbar(
    title,
    subTitle ?? '',
    messageText:
        StringUtils.isNullOrEmpty(subTitle) ? const SizedBox.shrink() : null,
    duration: const Duration(seconds: 1),
    padding: const EdgeInsets.all(15),
    margin: const EdgeInsets.only(bottom: 20, left: 20, right: 20),
  );
}`

**Comment by dimas-ibnu** [comment]
i'm facing same issue

**Comment by thiagotalma** [comment]
same here 

It's an old problem https://github.com/jonataslaw/getx/issues/2257

I don't know what priority they are giving to resolve the issue.

Unfortunately, it seems like it's not high enough.
