### ISSUE TITLE
Get.Key is not working

### ISSUE THREAD

**Issue by selvam920** [jonataslaw/getx#2887]
return MaterialApp(,
          debugShowCheckedModeBanner: false,
          navigatorKey: Get.key,
)

error
#0      GetRootState.controller (package:get/get_navigation/src/root/get_root.dart:314:7)
get_root.dart:314
#1      GetNavigationExt.rootController (package:get/get_navigation/src/extension_navigation.dart:1229:51)
extension_navigation.dart:1229
#2      GetNavigationExt.key (package:get/get_navigation/src/extension_navigation.dart:1225:40)

**Comment by alok2811** [comment]
Weap with GetMaterialApp
