### ISSUE TITLE
Get.lazyPut doesn't work as expected

### ISSUE THREAD

**Issue by rockerhieu** [jonataslaw/getx#293]
**Describe the bug**
Call `Get.lazyPut(() => SomeService())` in `GetMaterialApp.initialBinding`, but no dependency found with `Get.find<SomeService>()` later on.

`Get.put(SomeService())` works fine, but not `Get.lazyPut(() => SomeService())`.

**To Reproduce**
1. Click on 'Go to Other page'
2. See error
```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following message was thrown while handling a gesture:
 SomeService not found. You need call put<SomeService>(SomeService()) before

When the exception was thrown, this was the stack: 
#0      GetInstance.find (package:get/src/get_instance.dart:154:9)
#1      Storage.find (package:get/src/extension_instance.dart:14:21)
#2      new OtherBloc (package:getxexample/main.dart:109:27)
#3      OtherBindings.dependencies (package:getxexample/main.dart:103:13)
#4      new GetRouteBase (package:get/src/routes/default_route.dart:50:15)
...
```
**Expected behavior**
There should be no error and `Get.find<SomeService>()` should trigger the injected dependency with `lazyPut`.

**Flutter Version:**
17.3.1

**Get Version:**
2.14.1

**Minimal reproduce code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyAppBinding implements Bindings {
  @override
  void dependencies() {
    // this works fine
    // Get.put(SomeService());

    // but not this
    Get.lazyPut(() => SomeService());
  }
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      initialRoute: '/home',
      initialBinding: MyAppBinding(),
      getPages: _getPages(),
    );
  }

  List<GetPage> _getPages() {
    return [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/other',
        page: () => OtherPage(),
        binding: OtherBindings(),
      ),
    ];
  }
}

class HomePage extends StatelessWidget {
  const HomePage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Home'),
            RaisedButton(
              onPressed: () {
                Get.toNamed('/other');
              },
              child: Text('Go to Other page'),
            )
          ],
        ),
      ),
    );
  }
}

class OtherPage extends StatelessWidget {
  const OtherPage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetX<OtherBloc>(
      builder: (bloc) => Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Counter: ${bloc.count.value}'),
              Text('SomeService: ${SomeService.instanceCount} instances'),
              RaisedButton(
                onPressed: () => bloc.count.value++,
                child: Text('+'),
              ),
              RaisedButton(
                onPressed: () => Get.offAllNamed('/home'),
                child: Text('Go Back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class OtherBindings implements Bindings {
  @override
  void dependencies() {
    Get.put(OtherBloc());
  }
}

class OtherBloc extends BaseBloc {
  var count = 0.obs;
  final someService = Get.find<SomeService>();
}

class BaseBloc extends RxController {}

class SomeService {
  static int instanceCount = 0;

  SomeService() {
    instanceCount++;
    assert(instanceCount == 1);
  }
}
```

**Comment by ghprod** [comment]
If you want to able access `SomeService` from other page, then you need to put `put` at `runApp`. cmiiw

**Comment by jonataslaw** [comment]
Get.lazyPut receives a function, so it doesn't know what type of class it is receiving, only Get.put knows, so it is mandatory to type Get.lazyput.
So always change this:
Get.lazyPut(() => SomeService());
for this:
Get.lazyPut<SomeService>(() => SomeService());

**Comment by jonataslaw** [comment]
I think this is not in the documentation, if not, I will insert it now.

**Comment by rockerhieu** [comment]
Cool, `Get.lazyPut<SomeService>(() => SomeService());` works for me. Thanks!

**Comment by rockerhieu** [comment]
@jonataslaw: the issue happen again if I go back and forth between pages:
1. Click on `Go to Other page`
2. Click on `Go Back`
3. See error
```
The following message was thrown building Builder(dirty):
 SomeService not found. You need call put<SomeService>(SomeService()) before

The relevant error-causing widget was: 
  GetMaterialApp file:///Users/hhua/Development/getx_example/lib/main.dart:23:12
When the exception was thrown, this was the stack: 
#0      GetInstance.find (package:get/src/get_instance.dart:153:9)
#1      Storage.find (package:get/src/extension_instance.dart:15:21)
#2      new OtherBloc (package:getxexample/main.dart:161:27)
#3      OtherBindings.dependencies (package:getxexample/main.dart:150:13)
#4      new GetPageRoute.<anonymous closure> (package:get/src/routes/default_route.dart:42:23)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Here's the code:
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyAppBinding implements Bindings {
  @override
  void dependencies() {
    // this works fine
    // Get.put(SomeService());

    // but not this
    Get.lazyPut<SomeService>(() => SomeService.shared);
  }
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      initialRoute: '/home',
      initialBinding: MyAppBinding(),
      getPages: _getPages(),
    );
  }

  List<GetPage> _getPages() {
    return [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/other',
        page: () => OtherPage(),
        binding: OtherBindings(),
      ),
    ];
  }
}

class HomePage extends StatelessWidget {
  const HomePage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Home'),
            RaisedButton(
              onPressed: () {
                Get.offAllNamed('/other');
              },
              child: Text('Go to Other page'),
            )
          ],
        ),
      ),
    );
  }
}

class OtherPage extends StatelessWidget {
  const OtherPage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            GetX<OtherBloc>(
              builder: (bloc) {
                print('counter 1 rebuilt');
                return Text(
                  'Counter: ${bloc.counter1.value}',
                );
              },
            ),
            GetX<OtherBloc>(
              builder: (bloc) {
                print('counter 2 rebuilt');
                return Text(
                  'Counter: ${bloc.counter2.value}',
                );
              },
            ),
            GetX<OtherBloc>(
              builder: (bloc) {
                print('sum rebuilt');
                return Text(
                  'Counter: ${bloc.sum}',
                );
              },
            ),
            GetX<OtherBloc>(
              builder: (bloc) {
                return TextField(
                  controller: bloc.editingController,
                  decoration: InputDecoration(
                    labelText: 'Counter 1 value',
                  ),
                );
              },
            ),
            GetX<OtherBloc>(
              builder: (bloc) {
                print('button 1 rebuilt');
                return RaisedButton(
                  onPressed: bloc.increaseCounter1,
                  child: Text('counter 1 ++'),
                );
              },
            ),
            GetX<OtherBloc>(
              builder: (bloc) {
                print('button 2 rebuilt');
                return RaisedButton(
                  onPressed: bloc.increaseCounter2,
                  child: Text('counter 2 ++'),
                );
              },
            ),
            RaisedButton(
              onPressed: () => Get.offAllNamed('/home'),
              child: Text('Go Back'),
            ),
          ],
        ),
      ),
    );
  }
}

class OtherBindings implements Bindings {
  @override
  void dependencies() {
    Get.put(OtherBloc());
  }
}

class OtherBloc extends BaseBloc {
  final editingController = TextController();
  var counter1 = 0.obs;
  var counter2 = 0.obs;

  int get sum => counter1.value + counter2.value;

  final someService = Get.find<SomeService>();

  @override
  void onInit() {
    super.onInit();
    editingController.addListener(_textChanged);
  }

  @override
  void onClose() {
    editingController.removeListener(_textChanged);
    super.onClose();
  }

  void _textChanged() {
    counter1.value = int.tryParse(editingController.text) ?? 0;
  }

  void increaseCounter1() {
    counter1.value++;
    editingController.text = '${counter1.value}';
  }

  void increaseCounter2() {
    counter2.value++;
  }
}

class TextController extends TextEditingController {
  @override
  void dispose() {
    print('$this is being disposed');
    super.dispose();
  }
}

class BaseBloc extends GetxController {}

class SomeService {
  static SomeService shared = SomeService._();

  SomeService._();

  factory SomeService() {
    return shared;
  }
}
```

**Comment by jonataslaw** [comment]
You are initializing SomeService only on OtherPage.
If you get out of it, SomeService is discarded from memory, and there is no Binding on routes to make you live again.
Maybe using smartManagement: SmartManagement.keepFactory will help you until you understand the dynamics of Get, it is much easier to deal with. I created just one initialBindings, and put all your dependencies on it, regardless of where you are going to use it.
Remove the Bindings from the routes, and there you go, you will have no problems.
When you understand the dynamics of disposition, you can try something like the full method, which discards the factories, and needs some initialization logic and dispose of them.

**Comment by rockerhieu** [comment]
Where should a look at to understand the dynamic of disposition? Is there any equivalent to scope (from Dagger) in Get?

**Comment by rockerhieu** [comment]
Would be great if there is a `Unbindings` class that I can unbinding all the bindings myself.

**Comment by pinguluk** [comment]
Got the same problem and SmartManagement.keepFactory doesn't work, only SmartManagement.onlyBuilder, but they are keeped in the memory

**Comment by chhamed** [comment]
using fenix: true works for me
```
Get.lazyPut<SessionScreenManagmentController>(
        () => SessionScreenManagmentController(),
        fenix: true);
```
