### ISSUE TITLE
Null check operator used on a null value  when deep linking added

### ISSUE THREAD

**Issue by AbirAppDevs** [jonataslaw/getx#3040]
**Describe the bug**
Deep Linking
I working on deep link, it is working fine without getx, and when i use getx if not close app it is working,
but when i close the app it is showing errors.

![image](https://github.com/jonataslaw/getx/assets/156082638/5d384af5-c145-4380-a9dc-03d877e11354)
![image](https://github.com/jonataslaw/getx/assets/156082638/b40a3abd-520c-46bf-97c9-47b68cc93443)
![image](https://github.com/jonataslaw/getx/assets/156082638/04e06a60-9e8c-4428-9ae6-d489f9b07b9e)

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

```dart
/// main file 
void main() async {
  ....
  ...
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(414, 896),
      builder: (_, child) => GetMaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          textTheme: ThemeData.light().textTheme.apply(
                fontFamily: 'Roboto',
              ),
          bottomSheetTheme:
              const BottomSheetThemeData(backgroundColor: Colors.transparent),
        ),
        initialRoute: Routes.splashScreen,
        getPages: Routes.list,
        navigatorKey: Get.key,
        initialBinding: BindingsBuilder(() async{
          Get.put(SettingController(), permanent: true);
          await DynamicLanguage.init(url: ApiEndpoint.languageURL);
        }),
        builder: (context, widget) {
          ScreenUtil.init(context);
          return Obx(
            () => MediaQuery(
              data: MediaQuery.of(context)
                  .copyWith(textScaler: TextScaler.linear(1.0)),
              child: Directionality(
                textDirection: DynamicLanguage.isLoading
                    ? TextDirection.ltr
                    : DynamicLanguage.languageDirection,
                child: widget!,
              ),
            ),
          );
        },
      ),
    );
  }
}




/// route
static var list = [
    GetPage(
      name: splashScreen,
      page: () => const SplashScreen(),
      binding: SplashBinding(),
    ),

    GetPage(
        name: '/details/values/:pathdId',
        page: () => DeepLinkScreen(id: Get.parameters["pathdId"] ?? "")
    ),
]

```

**Video**
https://drive.google.com/file/d/1c9MU7EHmcevsEp2pNr-8Ny4kjPGKlYde/view?usp=sharing

**Screenshots*
deep link when Close App
![image](https://github.com/jonataslaw/getx/assets/156082638/f2b702e7-c998-4bc0-a59b-c3e6c0d6380f)
 

**Flutter Version:**
(sdk: '>=3.2.5 <4.1.0')

**Getx Version:**
(get: 4.6.6)

**Comment by AbirAppDevs** [comment]
adb shell am start -a android.intent.action.VIEW     -c android.intent.category.BROWSABLE     -d http://exampletest.com/details/values/12436892nece    net.appdevs.walletium

I am testing deep link by command


Please guide me how to solve this error?

My WhatsApp Number +8801877348044
Email: abir.appdevs@gmail.com

**Comment by LidiiaPl** [comment]
I'm facing the same error currently. Any updates?

**Comment by AbirAppDevs** [comment]
No havent find any solution
it is maybe from getx,,
i am using uni links for getx now it is working on emulator but not in real device in release version
[LidiiaPl](https://github.com/LidiiaPl)

**Comment by AbirAppDevs** [comment]
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
i found that for this it is showing this error..
if i remove this .. it is okay

**Comment by Sarathlal13** [comment]
Same issue here 
#440    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
framework.dart:4335
#441    Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
framework.dart:3846
#442    RootElement._rebuild (package:flutter/src/widgets/binding.dart:1354:16)
binding.dart:1354
#443    RootElement.mount (package:flutter/src/widgets/binding.dart:1323:5)
binding.dart:1323
#444    RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1276:18)
binding.dart:1276
#445    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844:19)
framework.dart:2844
#446    RootWidget.attach (package:flutter/src/widgets/binding.dart:1275:13)
binding.dart:1275
#447    WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1088:27)
binding.dart:1088
#448    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1070:5)
binding.dart:1070
#449    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1056:7)
binding.dart:1056
#453    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
isolate_patch.dart:184
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was:

**Comment by nandakista** [comment]
Hello guys, I have same issue before
after spending a lot of time I found two the solutions that you can choose
1. Make sure the initialRoutes is `'/'`
or
2. When the deeplink came from cold start, its always open the `'/'` as initial route and if your initial route name is not `'/'`, getx throw to the unknown route property so you must set `unknownRoute` in the `GetMaterialApp`
<details><summary>See the code here</summary><img width="740" alt="Screenshot 2024-03-02 at 21 04 32" src="https://github.com/jonataslaw/getx/assets/47182823/0c32365d-a558-49da-aeaa-707a046132b1"></details>


Hope this help you guys @AbirAppDevs @Sarathlal13

**Comment by AbirAppDevs** [comment]
@nandakista 
Thanks a Lot my dear...

**Comment by Matix-Media** [comment]
Hey, I've tried setting unknownRoute and initialRoute and sadly that both did not work.. Is there a solution or are the getx developers maybe trying to fix this??

**Comment by homedev-repo** [comment]
> Olá, tentei definir unknownRoute e initialRoute e, infelizmente, ambos não funcionaram. Existe uma solução ou os desenvolvedores do getx estão tentando consertar isso?
> 
> Editar: A única coisa que funcionou para mim foi desabilitar o tratamento padrão de deeplink do Flutter usando: Android:
> 
>             <meta-data android:name="flutter_deeplinking_enabled" android:value="false" />
> iOS:
> 
>         <key>FlutterDeepLinkingEnabled</key>
>         <false />
> E gerenciando links de aplicativos e links profundos eu mesmo.

resolve to me thanks

**Comment by hungify** [comment]
@homedev-repo 
Hey friend, I have the same issue. I’m unsure how to read this link from brach.io: `URI scheme: muscle://open?link_click_id=1444366189323482610 I/SurfaceView@e7f14eb`. Do you have any ideas?
I'm trying to use the Branch.io Flutter SDK, but it doesn't work.

**Comment by Strime** [comment]
Hi. Nothing new about this ?
