### ISSUE TITLE
NoSuchMethodError: The getter 'name' was called on null. When using NestedNavigator.

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/getx#313]
**Describe the bug**
I have an app with a Bottom navigation bar and an IndexedStack for handling multiple views.
Some of the views have a NestedNavigator, after upgrading to Get v3 I now get

```sh
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Builder(dirty):
The getter 'name' was called on null.
Receiver: null
Tried calling: name

The relevant error-causing widget was: 
  Navigator-[LabeledGlobalKey<NavigatorState>#d9055] file:///home/havoc/AndroidStudioProjects/pointograph_app/lib/places/places_main/places_main.dart:36:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new GetPageRoute.<anonymous closure> (package:get/src/routes/default_route.dart:49:47)
#2      PageRouteBuilder.buildPage (package:flutter/src/widgets/pages.dart:101:23)
#3      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:804:43)
#4      Builder.build (package:flutter/src/widgets/basic.dart:6998:48)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
**Flutter Version:**
v1.17.3

**Get Version:**
3.1.2

**Minimal reproduce code**
```dart
Navigator(
    key: Get.nestedKey(1),
    initialRoute: '/profile',
    onGenerateRoute: (routeSettings) {
      print(routeSettings);
      switch (routeSettings.name) {
        case '/profile':
          return GetPageRoute(
            page: () => ProfileHomeView(),
            transition: Transition.noTransition,
          );
        default:
          return GetPageRoute(page: () => ErrorRoute());
      }
    },
  );
```
In the previous version, this was
```dart
Navigator(
    key: Get.nestedKey(1),
    initialRoute: '/profile',
    onGenerateRoute: (routeSettings) {
      print(routeSettings);
      switch (routeSettings.name) {
        case '/profile':
          return GetRouteBase(
            page: ProfileHomeView(),
          );
        default:
          return GetRouteBase(page:ErrorRoute());
      }
    },
  );
```

Also, note that adding the settings parameter fixes this.
```dart
Navigator(
    key: Get.nestedKey(1),
    initialRoute: '/profile',
    onGenerateRoute: (routeSettings) {
      print(routeSettings);
      switch (routeSettings.name) {
        case '/profile':
          return GetPageRoute(
            settings: routeSettings,
            page: () => ProfileHomeView(),
            transition: Transition.noTransition,
          );
        default:
          return GetPageRoute(page: () => ErrorRoute());
      }
    },
  );
```

**Comment by jonataslaw** [comment]
settings is mandatory now because of the web urls.
Apparently Flutter needs this to display the name in the url correctly.
I used to send an empty class in case it is empty, but as we changed from PageRoute to PageRouteBuilder to allow customTransitions, this became mandatory.
I think I will insert an assert to give an error so that the user knows that a 'settings: settings' is missing

**Comment by Prn-Ice** [comment]
Thanks, will do, feel free to close.
