### ISSUE TITLE
GetRouterOutlet + IndexedRouteBuilder run error

### ISSUE THREAD

**Issue by LiuPack** [jonataslaw/getx#3248]
demo in [getx5_example](https://github.com/LiuPack/getx5_example)
Flutter version is **Channel stable, 3.24.3**
![Screenshot_20241026_230413](https://github.com/user-attachments/assets/9eeb8758-0eac-45bc-b9a1-4ecfa0ffb392)
```
Launching lib/main.dart on sdk gphone16k arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Debug service listening on ws://127.0.0.1:57283/O_Ljuw3cJTQ=/ws
Syncing files to device sdk gphone16k arm64...
I/k.getx5_example(11104): Compiler allocated 5250KB to compile void android.view.ViewRootImpl.performTraversals()
[GETX] GetDelegate is created !
[GETX] GetInformationParser is created !
[GETX] GetInformationParser: route location: /
[GETX] GOING TO ROUTE /
[GETX] GetDelegate is created !
[GETX] GetDelegate is created !

======== Exception caught by widgets library =======================================================
The following assertion was thrown building InheritedNavigator:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5675 pos 12: 'child == _child': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  InheritedNavigator InheritedNavigator:file:///Users/liuxin/.pub-cache/hosted/pub.dev/get-5.0.0-release-candidate-9.2.1/lib/get_navigation/src/routes/router_outlet.dart:130:22
When the exception was thrown, this was the stack: 
#2      ComponentElement.forgetChild (package:flutter/src/widgets/framework.dart:5675:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:4393:14)
...     Normal element mounting (39 frames)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#43     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#44     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (160 frames)
#204    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#205    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#206    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (150 frames)
#356    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#357    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#358    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (115 frames)
#473    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#474    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#475    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (160 frames)
#635    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#636    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#637    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (150 frames)
#787    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#788    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#789    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (115 frames)
#904    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#905    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#906    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (134 frames)
#1040   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#1041   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#1042   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (150 frames)
#1192   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#1193   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#1194   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (77 frames)
#1271   Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#1272   Element.updateChild (package:flutter/src/widgets/framework.dart:3957:20)
#1273   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#1274   Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#1275   StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#1276   Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#1277   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#1278   Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#1279   ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#1280   Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#1281   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#1282   Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#1283   ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#1284   Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#1285   ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#1286   StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#1287   Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#1288   BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#1289   BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#1290   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#1291   WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#1292   RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#1293   SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#1294   SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#1295   SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
#1296   PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#1300   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
D/ProfileInstaller(11104): Installing profile for org.liupack.getx5_example

```

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by jonataslaw** [comment]
I think you forgot put root "/" in yours paths.
