### ISSUE TITLE
Getroot issue

### ISSUE THREAD

**Issue by faheemletitgo** [jonataslaw/getx#3272]
why i am getting this issue 

`W/.example.beboro( 2726): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~Gsh58LruPcK525XUQgoVCg==/com.google.android.marvin.talkback-qw-d3bgd-eLxXID8xwKpYA==/base.apk' with 1 weak references
W/.example.beboro( 2726): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~Gsh58LruPcK525XUQgoVCg==/com.google.android.marvin.talkback-qw-d3bgd-eLxXID8xwKpYA==/split_config.arm64_v8a.apk' with 1 weak references
W/.example.beboro( 2726): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~F4auGj55S8govfceCgan-w==/cn.wps.moffice_eng-M0Z4wEedGBiCUs_2Gu7cKA==/base.apk' with 1 weak references
W/.example.beboro( 2726): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~F4auGj55S8govfceCgan-w==/cn.wps.moffice_eng-M0Z4wEedGBiCUs_2Gu7cKA==/split_config.arm64_v8a.apk' with 1 weak references
W/.example.beboro( 2726): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~F4auGj55S8govfceCgan-w==/cn.wps.moffice_eng-M0Z4wEedGBiCUs_2Gu7cKA==/split_config.en.apk' with 1 weak references
W/.example.beboro( 2726): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~F4auGj55S8govfceCgan-w==/cn.wps.moffice_eng-M0Z4wEedGBiCUs_2Gu7cKA==/split_config.xxhdpi.apk' with 1 weak references
D/VRI[MainActivity]( 2726): visibilityChanged oldVisibility=true newVisibility=false
I/AutofillManager( 2726): onInvisibleForAutofill(): expiringResponse
W/WindowOnBackDispatcher( 2726): sendCancelIfRunning: isInProgress=false callback=android.app.Activity$$ExternalSyntheticLambda0@dd5b9ef
D/FlutterGeolocator( 2726): Detaching Geolocator from activity
D/FlutterGeolocator( 2726): Flutter engine disconnected. Connected engine count 1
D/FlutterGeolocator( 2726): Disposing Geolocator services
E/FlutterGeolocator( 2726): Geolocator position updates stopped
E/FlutterGeolocator( 2726): There is still another flutter engine connected, not stopping location service
I/Choreographer( 2726): Skipped 71 frames!  The application may be doing too much work on its main thread.
D/FLTFireContextHolder( 2726): received application context.
D/FlutterGeolocator( 2726): Attaching Geolocator to activity
I/ContentCaptureHelper( 2726): Setting logging level to OFF
D/FlutterGeolocator( 2726): Geolocator foreground service connected
D/FlutterGeolocator( 2726): Initializing Geolocator services
D/FlutterGeolocator( 2726): Flutter engine connected. Connected engine count 2
D/WindowLayoutComponentImpl( 2726): Register WindowLayoutInfoListener on Context=com.example.beboro.MainActivity@b01881c, of which baseContext=android.app.ContextImpl@b8aa7d9
[GETX] Instance "FirebaseNotificationController" has been created
[GETX] Instance "FirebaseNotificationController" has been initialized
I/flutter ( 2726): Skipping Pusher initialization - No auth token
I/flutter ( 2726): User granted permission: AuthorizationStatus.authorized
[GETX] Instance "AuthController" has been created
[GETX] Instance "AuthController" has been initialized
[GETX] Instance "BottomNavigationController" has been created
[GETX] Instance "BottomNavigationController" has been initialized
[GETX] Instance "NavigationDrawerController" has been created
[GETX] Instance "NavigationDrawerController" has been initialized
[GETX] Instance "MainScreenBinding" has been created
[GETX] Instance "EarningsBinding" has been created
[GETX] Instance "EditItemBinding" has been created
[GETX] Instance "ResumeAdBinding" has been created
[GETX] Instance "ListingBinding" has been created
[GETX] Instance "AccountInformationBinding" has been created
[GETX] Instance "AddAnItemToListBinding" has been created
[GETX] Instance "AdvertiseWithUsBinding" has been created
[GETX] Instance "MakeOfferScreenOneBinding" has been created
[GETX] Instance "RenteeRentBookingsViewTabContainerBinding" has been created
[GETX] Instance "ActivePastRentalsTabContainerBinding" has been created
[GETX] Instance "ChooseDatesTabContainerBinding" has been created
[GETX] Instance "CheckoutBinding" has been created
[GETX] Instance "CheckoutReceiptBinding" has been created
[GETX] Instance "LoginScreenMainBinding" has been created
[GETX] Instance "IdVerificationBinding" has been created
[GETX] Instance "SelfieVerificationBinding" has been created
[GETX] Instance "TypeOfVerificationBinding" has been created
[GETX] Instance "UploadVerificationDocsScreenBinding" has been created
[GETX] Instance "ReportUserAllListingsBinding" has been created
[GETX] Instance "SeeAllReviewBinding" has been created
[GETX] Instance "ReportUserBinding" has been created
[GETX] Instance "OfferForRenterSideBinding" has been created
[GETX] Instance "OfferForRenterSideScreenIncreaseDescreaseBinding" has been created
[GETX] Instance "MakeOfferBinding" has been created
[GETX] Instance "OfferForRenterSideOneBinding" has been created
[GETX] Instance "RenteeMessageBinding" has been created
[GETX] Instance "SavedItemsPageBinding" has been created
[GETX] Instance "FilterSearchBinding" has been created
[GETX] Instance "CheckoutScreenFirstBinding" has been created
[GETX] Instance "LenderNotificationBinding" has been created
[GETX] Instance "DisputeScreenBinding" has been created
[GETX] Instance "CardOneBinding" has been created
[GETX] Instance "UserProfileController" has been created
[GETX] Instance "UserProfileController" has been initialized
[GETX] Instance "UserPostsController" has been created
[GETX] Instance "UserPostsController" has been initialized
[GETX] Instance "MyChatsController" has been created

════════ Exception caught by widgets library ═══════════════════════════════════
The following _Exception was thrown building LayoutBuilder:
Exception: GetRoot is not part of the three

The relevant error-causing widget was:
    OrientationBuilder OrientationBuilder:file:///C:/Users/fisfo/OneDrive/Documents/GitHub/beboro/lib/core/utils/size_utils.dart:28:14

When the exception was thrown, this was the stack:
#0      GetRootState.controller (package:get/get_navigation/src/root/get_root.dart:318:7)
#1      GetNavigationExt._getxController (package:get/get_navigation/src/extension_navigation.dart:1305:50)
#2      GetNavigationExt.routing (package:get/get_navigation/src/extension_navigation.dart:1326:26)
#3      GetNavigationExt.currentRoute (package:get/get_navigation/src/extension_navigation.dart:1189:30)
#4      MyChatsController.onInit (package:beboro/presentation/chat/mychats/controller/my_chats_controller.dart:26:14)
#5      GetLifeCycleMixin.onStart (package:get/get_instance/src/lifecycle.dart:51:5)
#6      Inst._startController (package:get/get_instance/src/extension_instance.dart:250:9)
#7      Inst._initDependencies (package:get/get_instance/src/extension_instance.dart:200:11)
#8      Inst.find (package:get/get_instance/src/extension_instance.dart:293:17)
#9      Inst.put (package:get/get_instance/src/extension_instance.dart:83:12)
#10     Bind.put (package:get/get_state_manager/src/simple/get_state.dart:127:9)
#11     AppRoutes.bindings (package:beboro/routes/app_routes.dart:241:10)
#12     AppRoutes.bindings (package:beboro/routes/app_routes.dart)
#13     MyApp.build.<anonymous closure> (package:beboro/main.dart:105:24)
#14     Sizer.build.<anonymous closure>.<anonymous closure> (package:beboro/core/utils/size_utils.dart:30:23)
#15     OrientationBuilder._buildWithConstraints (package:flutter/src/widgets/orientation_builder.dart:47:19)
#16     _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:191:77)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
#18     _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:231:12)
#19     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2719:59)
#20     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1098:15)
#21     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2719:14)
#22     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:278:5)
#23     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:369:5)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#25     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:371:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#27     RenderView.performLayout (package:flutter/src/rendering/view.dart:281:14)
#28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#30     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#31     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#32     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#33     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#34     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#35     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#36     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
#37     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#41     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════
I/flutter ( 2726): Fetching profile with token: null
I/flutter ( 2726): Current token: null
I/flutter ( 2726): FCM Token: dRVyl4VbQJ6BbjczNISqit:APA91bFjHBGxnJP2JzhLri7iYZuhb2nkbt47w4vlAcUbtyd-jPv2UrQDOiY7O4R9ImZ4meWktyiAthImdXmtm9yM-gPuqcah9pu8pAZgB82zW8G7R0mDGJ0
W/FLTFireMsgService( 2726): Attempted to start a duplicate background isolate. Returning...
`

**Comment by jonataslaw** [comment]
Please, show me the `size_utils.dart:28:14` code.
