### ISSUE TITLE
Unhandled Exception: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by ialameh** [jonataslaw/getx#351]
Hi,

I have two classes extending the GetXController: AuthenticationService and AppDatabase

in both classes I have onInit

in AuthenticationService

```dart
@override
  onInit() async {
    user.bindStream(FirebaseAuth.instance.onAuthStateChanged);
    ever(user, (value) { user.value = value;
    try {
        uid.value = user.value.uid;
      } catch (e) {
        uid.value = '';
      }
    });
	
```

in AppDatabase

 ```dart
 @override
  onInit() async{
   try {
     snapshot.value = await profileCollection.document(authenticationService.uid.value).get();
   } catch (e) {
     // TODO
     print('still not logged in');
   }
    snapshot.bindStream(profileCollection.document(authenticationService.uid.value).snapshots());
    ever(snapshot, (value) {
      snapshot.value = value;
    });
  super.onInit();
  }
```
  
In home (my view)
```dart

  final AuthenticationService _ = Get.put<AuthenticationService>(AuthenticationService());
  final AppDatabase db = AppDatabase.to; // (AppDatabase put is in main)
  
  
```
  my builder: 
```dart
  
  return GetX<AuthenticationService>(
      builder: (b) {
	  
```
and this is how I display content of firstname that is in the database (to debug)
`(db.snapshot.value != null )? Text("${db.snapshot.value.data['firstname']}") : Text('none'),`

whenever i make change to firstname in the database, the change is received to the app, however I get this error

```
E/flutter (24073): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter (24073): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
E/flutter (24073): #1      _RxImpl.value= (package:get/src/rx/rx_impl.dart:55:13)
E/flutter (24073): #2      _RxImpl.bindStream.<anonymous closure> (package:get/src/rx/rx_impl.dart:64:62)
E/flutter (24073): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (24073): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (24073): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (24073): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (24073): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (24073): #8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter (24073): #9      _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
E/flutter (24073): #10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (24073): #11     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (24073): #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (24073): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (24073): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (24073): #15     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (24073): #16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (24073): #17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (24073): #18     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (24073): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24073): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24073): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (24073): #22     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24073): #23     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24073): #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24073): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (24073): #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (24073): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (24073): 
```

Is there something wrong with the way I am doing it?

Sam

**Comment by ialameh** [comment]
I changed to 

   profileCollection.document(authenticationService.uid.value).snapshots().listen((value) {
     snapshot.value = value;
   });

and it worked well, I don't understand the difference between bindstream and listen

**Comment by ialameh** [comment]
it turns out that I was closing the stream when logging out using 
`snapshot.close();`

is this the right way to close the stream?

**Comment by ialameh** [comment]
To solve this, I had to put the stream opening inside the initState of the home page instead of onInit (I thought onInit will be called like what is in initState)
closing the stream was snapshot.close(); at the logout stage

**Comment by jonataslaw** [comment]
Hi, first it would be important to track which ".obs" is being used after closing, I believe that somewhere in the log it will point to a variable. You have some observable variables, so identifying which error is coming from would be important.

Second, where were you closing the streams? in the onClose method?

Third, are you using drain on the Stream before closing? Sometimes this is necessary.

**Comment by ialameh** [comment]
Here what worked well for me no errors, 
in database file

```
void onInit() async{
    snapshot.value = await profileCollection.document(authenticationService.uid.value).get();
    docStream.value = profileCollection
        .document(authenticationService.uid?.value)
        ?.snapshots()
        ?.listen((event) {
      snapshot?.value = event;
    });`
    super.onInit();
  }
}

```

in authentication file

```

  @override
  void onInit() {
    userStream.value =
        FirebaseAuth.instance.onAuthStateChanged.listen((event) {
          user.value = event;
          uid.value = event?.uid;
        });
    print('I AM HERE AND LISTENING - Authentication');

    super.onInit();
  }
```

on login I had to reassign a value to assign the value to snapshot, because it will be nulled when closing the steam

`    db.snapshot = Rx<DocumentSnapshot>();
`

upon logout close the stream
`
    db.docStream.value.cancel();
`


in initState, I had to call both onInit (isn't supposed that the GetX call onInit without specifying that)

```
initState (temp) { authenticationService.onInit();
db.onInit(); }

```

**Comment by cahyowhy** [comment]
up
