### ISSUE TITLE
Bottomsheet error

### ISSUE THREAD

**Issue by govindmaheshwari2** [jonataslaw/getx#474]
**Fill in the template. Issues that do not respect the model will be closed.**

getting error when opening bottomsheet
```
I/flutter (31699): [GETX] OPEN BOTTOMSHEET bottomsheet

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a
RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.
Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically,
Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.
The ownership chain for the RenderObject that received the incompatible parent data was:
  RepaintBoundary ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ←
Scrollable ← ListView ← Expanded ← Padding ← ColoredBox ← Container ←
NotificationListener<DraggableScrollableNotification> ← ⋯

When the exception was thrown, this was the stack:
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5689:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5705:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5726:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5420:5)
#4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5873:11)
...     Normal element mounting (268 frames)
#272    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#274    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5624:32)
#275    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
#276    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#277    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#278    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#279    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#280    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#283    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#284    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#285    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#287    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#288    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#289    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#290    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#291    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#292    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#294    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#295    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#296    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#297    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#298    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#299    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#300    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
#301    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#302    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#303    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#304    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#305    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#306    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#307    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#308    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#309    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#310    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#311    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#312    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#313    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#314    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#318    _invoke (dart:ui/hooks.dart:253:10)
#319    _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  RepaintBoundary ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ← Scrollable ← ListView ← Expanded ← Padding ← ColoredBox ← Container ← NotificationListener<DraggableScrollableNotification> ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5689:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5705:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5726:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5420:5)
#4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5873:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
**To Reproduce**
code added Below

**Expected behavior**
Bottomsheet is open without this error.

**Flutter Version:**
latest

**Get Version:**
3.4.4
**Describe on which device you found the bug:**
ex: Samsung Galaxy M30S

**Minimal reproduce code**
onTap:(){
Get.bottomSheet(bottomSlider(list[index]["Answer"]);
}

 Widget bottomSlider(answerList){
return Container(
child:Expanded(
child:ListView.builder(...)));
}

**Comment by jonataslaw** [comment]
```
return Container(
child:Expanded(

```
Take a look at the Flutter documentation about Expanded and flexible widgets.
Expanded can only be inside a Row or Column, and this error has nothing to do with Getx.
