### ISSUE TITLE
Change between 3.4.6 and 3.5.0/3.5.1 - All controllers are deleted from memory on app resume

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/getx#517]
**Describe the bug**
All controllers are deleted from memory upon app resume

**To Reproduce**
1. Use version 3.4.6 and all is well
2. Upgrade to 3.5.0 or 3.5.1 and controllers get removed from memory

**Expected behavior**
Normal behaviour in my app on 3.4.6 when app was backgrounded and resumed.

```
I/flutter (10352): [GETX] AuthController has been initialized
I/flutter (10352): [GETX] GetMaterialController has been initialized
I/flutter (10352): [GETX] GOING TO ROUTE /
I/flutter (10352): [GETX] REPLACE ROUTE /
I/flutter (10352): [GETX] NEW ROUTE /HomeScreen
I/flutter (10352): [GETX] HomeScreenController has been initialized
I/flutter (10352): [GETX] NotificationsController has been initialized
I/flutter (10352): Running CallController onInit();
I/flutter (10352): Ran _bindEventListeners();
I/flutter (10352): [GETX] CallController has been initialized
```

on 3.5.0 or 3.5.1 this happens when app was backgrounded and resumed.

```
I/flutter (32716): Loading isLoggedIn as "true" from device.
I/flutter (32716): [GETX] AuthController has been initialized
I/flutter (32716): [GETX] GetMaterialController has been initialized
I/flutter (32716): [GETX] REPLACE ROUTE /
I/flutter (32716): [GETX] NEW ROUTE null
I/flutter (32716): [GETX] REPLACE ROUTE null
I/flutter (32716): [GETX] NEW ROUTE null
I/flutter (32716): [GETX] HomeScreenController has been initialized
I/flutter (32716): [GETX] NotificationsController has been initialized
I/flutter (32716): Running CallController onInit();
I/flutter (32716): Ran _bindEventListeners();
I/flutter (32716): [GETX] CallController has been initialized
I/flutter (32716): Setting title to: Calls
I/flutter (32716): Building PageView at position: 0
I/flutter (32716): [GETX] CallsController instance was created at that time
I/flutter (32716): [GETX] CallsController has been initialized
I/flutter (32716): Setting title to: Calls
I/flutter (32716): Building PageView at position: 0
I/flutter (32716): [GETX] onClose of HomeScreenController called
I/flutter (32716): [GETX] HomeScreenController deleted from memory
I/flutter (32716): [GETX] onClose of NotificationsController called
I/flutter (32716): [GETX] NotificationsController deleted from memory
I/flutter (32716): [GETX] onClose of CallController called
I/flutter (32716): [GETX] CallController deleted from memory
I/flutter (32716): [GETX] Dio deleted from memory
I/flutter (32716): [GETX] CallsProvider deleted from memory
I/flutter (32716): [GETX] CallsRepository deleted from memory
I/flutter (32716): [GETX] onClose of CallsController called
I/flutter (32716): [GETX] CallsController deleted from memory
I/flutter (32716): Caught error: A ScrollPositionWithSingleContext was used after being disposed.
I/flutter (32716): Once you have called dispose() on a ScrollPositionWithSingleContext, it can no longer be used.
I/flutter (32716): stackTrace: #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier
```

**Flutter Version:**
```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.20.2 at /home/ghenry/development/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ghenry/Android/Sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /home/ghenry/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/ghenry/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5556 • android-x86 • Android 11 (API 30) (emulator)

```

**Get Version:**
3.4.6 working, 3.5.0 and 3.5.1 not.

**Describe on which device you found the bug:**
Android simulater Pixel 3a API 30, Samsung S10e Android 10, iPhone 8, iPhone SE 2nd11 Pro simulator

**Minimal reproduce code**
My Entry point is:

```
            initialBinding: InitialBinding(),
            home: SplashScreen()));
```

....
```
class InitialBinding implements Bindings {
  @override
  void dependencies() {
    Get.put(UserRepository());
    Get.put(AuthController());
  }
}
```

which is actually still just like this:

https://github.com/jonataslaw/getx/issues/223#issuecomment-642350349

Thanks.

**Comment by jonataslaw** [comment]
Does this behavior happen when the application goes to the background?

**Comment by ghenry** [comment]
I'll check.

**Comment by Nipodemos** [comment]
@ghenry anything new about this issue?

**Comment by ghenry** [comment]
Too scared to upgrade :) Will try over the weekend.

-- 
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@surevoip.co.uk

Open Telecoms for Business (tm).

http://www.surevoip.co.uk

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

OpenPGP (GPG/PGP) Public Key: 0x8CFBA8E6 - Import from
hkp://pool.subkeys.pgp.net
or http://www.suretecgroup.com/0x8CFBA8E6.gpg

**Comment by Nipodemos** [comment]
> Too scared to upgrade :) Will try over the weekend.

hahah, good luck 😄

**Comment by ghenry** [comment]
I can only learn something new, so no issues with that :D

**Comment by jonataslaw** [comment]
Could you please test with version 3.10.2 to see if the behavior persists?

**Comment by ghenry** [comment]
Will do.

**Comment by ghenry** [comment]
Hi @jonataslaw 

The issue is still there on 3.10.2 when I launch the app, click back to get out of it so it's backgrounded and then on launch again this:

```
[GETX] "AuthController" has been initialized
[GETX] "GetMaterialController" has been initialized
[GETX] REPLACE ROUTE /
[GETX] NEW ROUTE null
[GETX] REPLACE ROUTE null
[GETX] NEW ROUTE null
[GETX] "HomeScreenController" has been initialized
[GETX] "ContactsController" has been initialized
[GETX] "NotificationsController" has been initialized
[GETX] "SipController" has been initialized
I/flutter ( 6612): Running CallController onInit();
I/flutter ( 6612): Ran _bindEventListeners();
I/flutter ( 6612): Setting PackageInfo.
[GETX] "CallController" has been initialized
[GETX] Lazy instance "CallsController" created
[GETX] "CallsController" has been initialized

...

[GETX] "HomeScreenController" onClose() called
[GETX] "HomeScreenController" deleted from memory
[GETX] "ContactsProvider" deleted from memory
[GETX] "ContactsRepository" deleted from memory
[GETX] "ContactsController" onClose() called
[GETX] "ContactsController" deleted from memory
[GETX] "NotificationsController" onClose() called
[GETX] "NotificationsController" deleted from memory
[GETX] "SIPProvider" deleted from memory
[GETX] "SIPRepository" deleted from memory
[GETX] "SipController" onClose() called
[GETX] "SipController" deleted from memory
[GETX] "CallController" onClose() called
[GETX] "CallController" deleted from memory
[GETX] "Dio" deleted from memory
[GETX] "CallsProvider" deleted from memory
[GETX] "CallsRepository" deleted from memory
[GETX] "CallsController" onClose() called
[GETX] "CallsController" deleted from memory
I/flutter ( 6612): Caught error: A ScrollPositionWithSingleContext was used after being disposed.
I/flutter ( 6612): Once you have called dispose() on a ScrollPositionWithSingleContext, it can no longer be used.
I/flutter ( 6612): stackTrace: #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:108:9)
I/flutter ( 6612): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:114:6)
I/flutter ( 6612): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:203:12)
I/flutter ( 6612): #3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:810:11)
I/flutter ( 6612): #4      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:346:5)
I/flutter ( 6612): #5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:202:7)
I/flutter ( 6612): #6      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:181:7)
I/flutter ( 6612): #7      RefreshController.requestRefresh.<anonymous closure>.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:666:17)
I/flutter ( 6612): #8      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 6612): #9      _CustomZone.runUnary (dart:async/zone
I/flutter ( 6612): In dev mode. Not sending report to Sentry.io.
I/flutter ( 6612): Caught error: "CallsController" not found. You need to call "Get.put(CallsController())" or "Get.lazyPut(()=>CallsController())"
I/flutter ( 6612): stackTrace: #0      GetInstance.find (package:get/src/instance/get_instance.dart:240:9)
I/flutter ( 6612): #1      GetView.controller (package:get/src/state_manager/simple/get_view.dart:29:37)
I/flutter ( 6612): #2      CallsScreen._onRefresh (package:SureVoIPTalk/src/view/calls.dart:26:11)
I/flutter ( 6612): #3      RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:275:59)
I/flutter ( 6612): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:209:21)
I/flutter ( 6612): #5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:276:5)
I/flutter ( 6612): #6      RefreshController.requestRefresh.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:671:24)
I/flutter ( 6612): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 6612): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 6612): #9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
I/flutter ( 6612): #10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
I/flutter ( 6612): #11     Future._propagateT
I/flutter ( 6612): In dev mode. Not sending report to Sentry.io.
I/flutter ( 6612): Checking secure storage first.
```

I usually see:

```
I/flutter (10352): [GETX] AuthController has been initialized
I/flutter (10352): [GETX] GetMaterialController has been initialized
I/flutter (10352): [GETX] GOING TO ROUTE /
I/flutter (10352): [GETX] REPLACE ROUTE /
I/flutter (10352): [GETX] NEW ROUTE /HomeScreen
I/flutter (10352): [GETX] HomeScreenController has been initialized
I/flutter (10352): [GETX] NotificationsController has been initialized
I/flutter (10352): Running CallController onInit();
I/flutter (10352): Ran _bindEventListeners();
I/flutter (10352): Setting PackageInfo.
I/flutter (10352): [GETX] CallController has been initialized
```

For me, I'm going back to `3.4.6`

**Comment by tneotia** [comment]
This has been happening for me as well. I switched to Get.offAllNamed instead of just Get.offAll and it worked properly, strangely. Can you try this approach (or Get.offNamed/Get.toNamed) and see if it works properly?

**Comment by ghenry** [comment]
Hi Tanay,

I was thinking the same as I don't use named routes, just
Get.to(BlahScreen()); I only use Get.off and Get.offAll like so:

void checkLoggedIn(_) {
  // Maybe we move _loadLoggedIn in here. Check this works when we hit login.
  if (isLoggedIn.value) {
    Get.off(HomeScreen(), binding: CallsBinding());
  } else {
    Get.offAll(LoginScreen());
  }
}

**Comment by tneotia** [comment]
Ah I see. I had my GetMaterialApp setup as:
```
return new GetMaterialApp(
        title: 'MyApp',
        debugShowCheckedModeBanner: false,
        theme: lightTheme,
        darkTheme: darkTheme,
        themeMode: globalTheme == "Dark" || globalTheme == "Black" ? ThemeMode.dark : ThemeMode.light,
        initialRoute: '/',
        getPages: [
          GetPage(name: '/', page: () => LoginScreen()),
          GetPage(name: '/second', page: () => HomePage()),
          GetPage(name: '/third', page: () => SettingsScreen()),
etc....
        ],
      );
```
And then do
```
Get.offAllNamed('/second');
```

Maybe this setup is possible for your project?

**Comment by ghenry** [comment]
I may have to. My routes are full routes, but I use the screens which have
a global appBar/Scaffold via PageView.

**Comment by ghenry** [comment]
aren't full routes.

**Comment by Grohden** [comment]
Little offtopic, but @jonataslaw shouldn't `didReplace` be using `name` method to extract the route name? that null at the logs seemed weird

**Comment by tneotia** [comment]
@ghenry That's tricky then - would be a little bit of rewrite as PageView doesn't support named routes.

@Grohden that's why I decided to try `Get.toNamed/offNamed/offAllNamed` because I noticed the `null` in the logs. Don't know what changed the previous working behavior, maybe it's some commit that can be reverted.

**Comment by ghenry** [comment]
I'm upgrading now to 3.11.1 but hitting this before I even get started:

```
../../.pub-cache/hosted/pub.dartlang.org/get_storage-1.3.0/lib/src/storage_impl.dart:65:3: Error: Type 'Disposer' not found.
  Disposer listen(void Function() value) {
  ^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/get_storage-1.3.0/lib/src/storage_impl.dart:71:3: Error: Type 'Disposer' not found.
  Disposer listenKey(String key, Function(dynamic) callback) {
  ^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/get_storage-1.3.0/lib/src/storage_impl.dart:66:42: Error: The argument type 'void Function() Function(dynamic)' can't be assigned to the parameter type 'void Function()'.
    return _concrete.subject.addListener((e) => value);
                                         ^
../../.pub-cache/hosted/pub.dartlang.org/get_storage-1.3.0/lib/src/storage_impl.dart:79:42: Error: The argument type 'Null Function(dynamic)' can't be assigned to the parameter type 'void Function()'.
    return _concrete.subject.addListener(listen);
                                         ^
```

**Comment by ghenry** [comment]
My `pubspec` is like:

```
  # For firebase_messaging - https://github.com/FirebaseExtended/flutterfire/issues/3312
  platform: 3.0.0-nullsafety.1
  # For wiredash 0.3.0 on beta channels.
  file: 6.0.0-nullsafety.1
```

as on Flutter beta channel.

**Comment by ghenry** [comment]
Upgraded to 1.3.1 get_storage. Missed that. Now I'm seeing:

```
I/flutter (15303): Caught error: NoSuchMethodError: The method 'pushReplacementNamed' was called on null.
I/flutter (15303): Receiver: null
I/flutter (15303): Tried calling: pushReplacementNamed<dynamic, Object>("/home", arguments: null)
I/flutter (15303): stackTrace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (15303): #1      GetNavigation.offNamed (package:get_navigation/src/extension_navigation.dart:130:10)
I/flutter (15303): #2      AuthController.checkLoggedIn (package:SureVoIPTalk/src/controller/auth.dart:70:11)
I/flutter (15303): #3      ever.<anonymous closure> (package:get_rx/src/rx_workers/rx_workers.dart:47:42)
I/flutter (15303): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
```

**Comment by tneotia** [comment]
What's your code here and corresponding GetPage? Should be something like `Get.offNamed('/home', arguments: null)` for the code and `GetPage(name: '/home', page: () => Your_Page_Name()),` for the GetPage.

**Comment by jonataslaw** [comment]
> Upgraded to 1.3.1 get_storage. Missed that. Now I'm seeing:
> 
> ```
> I/flutter (15303): Caught error: NoSuchMethodError: The method 'pushReplacementNamed' was called on null.
> I/flutter (15303): Receiver: null
> I/flutter (15303): Tried calling: pushReplacementNamed<dynamic, Object>("/home", arguments: null)
> I/flutter (15303): stackTrace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> I/flutter (15303): #1      GetNavigation.offNamed (package:get_navigation/src/extension_navigation.dart:130:10)
> I/flutter (15303): #2      AuthController.checkLoggedIn (package:SureVoIPTalk/src/controller/auth.dart:70:11)
> I/flutter (15303): #3      ever.<anonymous closure> (package:get_rx/src/rx_workers/rx_workers.dart:47:42)
> I/flutter (15303): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
> ```

This only occurs when GetMaterialApp is not being used. This error is saying that pushReplacement was called null, because there is no navKey in your MaterialApp at the moment

**Comment by ghenry** [comment]
in my `app.dart` I have:

```
class SureVoIPTalkApp extends StatelessWidget {
  final _navigatorKey = GlobalKey<NavigatorState>();
  final FirebaseAnalytics analytics = FirebaseAnalytics();

  @override
  Widget build(BuildContext context) {
    return Wiredash(
        projectId: WIREDASH_PROJECT_ID,
        secret: WIREDASH_SECRET,
        navigatorKey: _navigatorKey,
        theme: WiredashThemeData(
            primaryColor: appColor,
            secondaryColor: appColor,
            dividerColor: Colors.white),
        options: WiredashOptionsData(

            /// Uncomment below to see how custom translations work
            // customTranslations: {
            //   const Locale.fromSubtags(languageCode: 'en'):
            //       const DemoCustomTranslations(),
            //   const Locale.fromSubtags(languageCode: 'pl'):
            //       const DemoPolishTranslations(),
            // },

            /// Uncomment below to override default device locale
            // locale: const Locale('de'),
            ),
        child: GetMaterialApp(
          localizationsDelegates: [
            const AppLocalizationsDelegate(),
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: [
            const Locale('en', ''), // English, no country code
            const Locale('fr', ''), // Hebrew, no country code
          ],
          navigatorKey: _navigatorKey,
...

          initialBinding: InitialBinding(),
          home: SplashScreen(),
          getPages: [
            GetPage(
                name: "/home",
                page: () => HomeScreen(),
                binding: HomeBinding()),
            GetPage(name: "/login", page: () => LoginScreen())
          ],
        ));
```

What should I do to resolve this then as I'll get a ton of Sentry alerts :-)

**Comment by ghenry** [comment]
So basically this original issue is gone now as I've switch to named routes, but I'm not sure if that was the issue and this switch resolved it.

**Comment by ghenry** [comment]
Going to close this now. Not happened since switch to Flutter beta channel and named routes with bindings.
