### ISSUE TITLE
Advance get.parameters value causes error

### ISSUE THREAD

**Issue by ariona** [jonataslaw/getx#521]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When the parameters value has some complex screen like space or characters it throw an error.
Below is the sample of my code calling Get.to with some complex params:
```dart
Get.toNamed('/web?url=https://site.amalsholeh.com/privasi/&title=Screen title');
```
And it throw an error:
```
═╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'page' was called on null.
Receiver: null
Tried calling: page
When the exception was thrown, this was the stack:
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      GetMaterialApp.generator                                                  package:get/…/root/root_widget.dart:123
#2      _WidgetsAppState._onGenerateRoute                              package:flutter/…/widgets/app.dart:1012
#3      NavigatorState._routeNamed                                            package:flutter/…/widgets/navigator.dart:3348
#4      NavigatorState.pushNamed                                              package:flutter/…/widgets/navigator.dart:3400
#5      GetNavigation.toNamed                                                    package:get/…/navigation/extension_navigation.dart:95
#6      _AccountScreenState.build.<anonymous closure>        package:myapp/…/account/index.dart:308
#7      _InkResponseState._handleTap                                         package:flutter/…/material/ink_well.dart:992
#8      _InkResponseState.build.<anonymous closure>            package:flutter/…/material/ink_well.dart:1098
#9      GestureRecognizer.invokeCallback                                  package:flutter/…/gestures/recognizer.dart:184
```
**To Reproduce**
1. Create named route
2. Use query param to pass some data
3. Use spaced value, like: *Screen Title*
4. Use mixed characters like: https://flutter.dev

**Expected behavior**
The parameters should be passed to the screen, thrown an error instead

**Flutter Version:**
Flutter SDK 1.20.2

**Get Version:**
Get ^3.5.1

**Describe on which device you found the bug:**
Pocophone F1

**Minimal reproduce code**
```
Get.toNamed('/web?url=https://site.amalsholeh.com/privasi/&title=Screen title');
```

**Comment by jonataslaw** [comment]
Does switching to Screen_title have the same behavior? I think there should be no spaces between parameters, this is not allowed even on the web

**Comment by ariona** [comment]
I think i get this working. By encoding the value to Uri Component and decode it when reading parameters.
```dart
MenuItem(
  onTap: () => Get.toNamed('/web?title=widget title&url=${Uri.encodeComponent("https://flutter.dev")}'),
  icon: Icon(FeatherIcons.star, size: 16, color: Colors.orange),
  label: "Berikan Rating untuk aplikasi"
)
```
And getting the parameters by:
```dart
final String url = Uri.decodeComponent(Get.parameters["url"]);
```
Strangely the spaced value work now, the one that caused the error was url string which can be resolved by `encodeComponent`.
