### ISSUE TITLE
example could not run and without any output on android

### ISSUE THREAD

**Issue by lorentz-wu** [jonataslaw/getx#586]
my flutter is 1.20.3 stable, build example and install example to android system, but it didn't run. I debug example but without any output, I try this on real phone and emulator.

**Comment by Grohden** [comment]
Would be nice to have a logcat for that.

But anyway, here's it:

```
2020-09-10 11:04:33.282 1375-3586/? D/OneplusAppPreload: getx.demo.app.example is not preload, collectAppFocusEvent
2020-09-10 11:02:14.634 5850-5850/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: getx.demo.app.example, PID: 5850
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{getx.demo.app.example/getx.demo.app.example.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "getx.demo.app.example.MainActivity" on path: DexPathList[[zip file "/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk"],nativeLibraryDirectories=[/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/lib/arm64, /data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3004)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3214)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "getx.demo.app.example.MainActivity" on path: DexPathList[[zip file "/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk"],nativeLibraryDirectories=[/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/lib/arm64, /data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1232)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2992)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3214) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-09-10 11:04:33.380 5924-5924/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: getx.demo.app.example, PID: 5924
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{getx.demo.app.example/getx.demo.app.example.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "getx.demo.app.example.MainActivity" on path: DexPathList[[zip file "/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk"],nativeLibraryDirectories=[/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/lib/arm64, /data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3004)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3214)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "getx.demo.app.example.MainActivity" on path: DexPathList[[zip file "/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk"],nativeLibraryDirectories=[/data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/lib/arm64, /data/app/getx.demo.app.example-4omQ9rGyVJ68ONh6UXAC0Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1232)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2992)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3214) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-09-10 11:04:33.397 1375-3586/? D/AbnormalMonitor: appCrash :getx.demo.app.example
```

I'm gonna have a look when I have time
