### ISSUE TITLE
Unhandled Exception: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by sukhcha-in** [jonataslaw/getx#725]
**Describe the bug**
What exception i'm not handling?
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
#1      _RxImpl.addListener.<anonymous closure>
package:get/…/rx_core/rx_impl.dart:147
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#9      _rootRun (dart:async/zone.dart:1182:47)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> <…>

```

**Reproduction code**
```dart
import 'dart:convert';

import 'package:app/models/apps_model.dart';
import 'package:app/utils/storage.dart';
import 'package:app/utils/stores.dart';
import 'package:get/get.dart';
import 'package:get/get_state_manager/get_state_manager.dart';

class AppLauncherController extends GetxController {
  static BrowserStorage browserStorage = BrowserStorage();
  AppsModel requested = Get.arguments;

  final Stores stores = Stores();

  RxList myTabs = [].obs;
  RxInt currentTab = 0.obs;
  RxBool isLoaded = false.obs;

  @override
  void onInit() {
    super.onInit();
    loadOldTabs();
  }

  void updateCurrentIndex(int index) {
    currentTab.value = index;
  }

  void closeTab(String storeID) {
    if (myTabs.contains(storeID)) {
      var tabToBeClosed = myTabs.indexOf(storeID);
      myTabs.remove(storeID);
      if ((myTabs.length - 1) < tabToBeClosed) {
        var finalTab = myTabs.length - 1;
        currentTab.value = finalTab;
      }
      updateTabs();
      if (myTabs.length.isLowerThan(1)) {
        Get.back();
      }
    }
  }

  void openTab() {
    if (myTabs.contains(requested.getId)) {
      currentTab.value = myTabs.indexOf(requested.getId);
    } else {
      myTabs.add(requested.getId);
      currentTab.value = myTabs.length - 1;
    }
    updateTabs();
  }

  void updateTabs() {
    browserStorage.setActiveTabs(jsonEncode(myTabs).toString());
  }

  void loadOldTabs() {
    var tabs = browserStorage.activeTabs.toString();
    if (tabs.isNotEmpty) {
      var json = jsonDecode(tabs) as List;
      myTabs.clear();
      for (var i = 0; i < json.length; i++) {
        myTabs.add(json[i]);
      }
    }
    openTab();
  }
}

```

**Expected behavior**
Everything just works fine in app but in debug console this warning appears

**Flutter Version:**
1.22.1

**Getx Version:**
3.13.2

**Describe on which device you found the bug:**
iPhone 11

**Comment by eduardoflorence** [comment]
Your code cannot be reproduced.
Place the code so that we can copy, paste and run.

**Comment by sukhcha-in** [comment]
> Your code cannot be reproduced.
> Place the code so that we can copy, paste and run.

I think that will be very difficult, sorry.

**Comment by jonataslaw** [comment]
Hi, try close project, use:
`flutter clean`

And recompile the project.
See if the problem persists.
It seems to me another cache problem.

**Comment by sukhcha-in** [comment]
> Hi, try close project, use:
> `flutter clean`
> 
> And recompile the project.
> See if the problem persists.
> It seems to me another cache problem.

The warning appears randomly, don't know what is causing that.

**Comment by EbrahimMosaaed** [comment]
I had the same error and after i encoded body while requesting data it's gone
**json.encode(body)**

**Comment by jonataslaw** [comment]
> > Hi, try close project, use:
> > `flutter clean`
> > And recompile the project.
> > See if the problem persists.
> > It seems to me another cache problem.
> 
> The warning appears randomly, don't know what is causing that.

Cache, flutter clean solves it :)
