### ISSUE TITLE
Weird Directionality widget Duration error

### ISSUE THREAD

**Issue by psrcek** [jonataslaw/getx#731]
**Describe the bug**
When I use GetMaterialApp sometimes a weird error is thrown when starting the application.

**Reproduction code**
I have no idea how to reproduce this as it is pretty random, if you could help me figure it out that'd be great. :)

**To Reproduce**
1. Just start the app

**Expected behavior**
I expected my app to be started correctly but instead I get a red screen with a failed assertion.

**Screenshots**
![image](https://user-images.githubusercontent.com/13370323/96694969-658b3000-1389-11eb-9d79-7617e72fabd0.png)

**Flutter Version:**
Channel beta, `1.23.0-18.1.pre`
also tried with stable, same issue

**Getx Version:**
`^3.12.1`, currently resolves to `3.12.2`

**Describe on which device you found the bug:**
Samsung SM-A515F

**Error:**
This line in the log says to me that this is a GetX issue, not a flutter one.
`file:///home/david/.pub-cache/hosted/pub.dartlang.org/get-3.13.2/lib/get_navigation/src/root/root_widget.dart:257:22`

This is the full error that is printed to the log upon app launch:
```log
[+1466 ms] I/flutter (12284): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (12284): The following assertion was thrown building Directionality(textDirection: ltr):
[        ] I/flutter (12284): 'package:flutter/src/widgets/routes.dart': Failed assertion: line 154 pos 12: 'duration != null &&
[        ] I/flutter (12284): duration >= Duration.zero': is not true.
[        ] I/flutter (12284): 
[        ] I/flutter (12284): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (12284): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (12284): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (12284):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (12284): 
[        ] I/flutter (12284): The relevant error-causing widget was:
[        ] I/flutter (12284):   Directionality
[        ] I/flutter (12284):   file:///home/david/.pub-cache/hosted/pub.dartlang.org/get-3.13.2/lib/get_navigation/src/root/root_widget.dart:257:22
[        ] I/flutter (12284): 
[        ] I/flutter (12284): When the exception was thrown, this was the stack:
[        ] I/flutter (12284): #2      TransitionRoute.createAnimationController (package:flutter/src/widgets/routes.dart:154:12)
[        ] I/flutter (12284): #3      TransitionRoute.install (package:flutter/src/widgets/routes.dart:201:19)
[        ] I/flutter (12284): #4      ModalRoute.install (package:flutter/src/widgets/routes.dart:1080:11)
[        ] I/flutter (12284): #5      _RouteEntry.handleAdd (package:flutter/src/widgets/navigator.dart:2905:11)
[        ] I/flutter (12284): #6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3734:17)
[        ] I/flutter (12284): #7      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3321:5)
[        ] I/flutter (12284): #8      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:980:5)
[        ] I/flutter (12284): #9      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:966:7)
[        ] I/flutter (12284): #10     NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3339:11)
[        ] I/flutter (12284): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4833:11)
[        ] I/flutter (12284): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
[        ] I/flutter (12284): ...     Normal element mounting (277 frames)
[        ] I/flutter (12284): #289    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
[        ] I/flutter (12284): #290    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
[        ] I/flutter (12284): #291    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1215:16)
[        ] I/flutter (12284): #292    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1186:5)
[        ] I/flutter (12284): #293    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1128:18)
[        ] I/flutter (12284): #294    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
[        ] I/flutter (12284): #295    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1127:13)
[        ] I/flutter (12284): #296    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:967:7)
[   +1 ms] I/flutter (12284): #297    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:948:7)
[        ] I/flutter (12284): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
[        ] I/flutter (12284): 
[        ] I/flutter (12284): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by eduardoflorence** [comment]
It does not seem to be an error related to GetX. Try using the channel stable version of Flutter and also execute the commands below in the terminal:
```
flutter clean
flutter pub cache repair
flutter pub get
```

**Comment by psrcek** [comment]
The error clearly mentions GetX. Don't just dismiss this as "not a GetX issue".
If this is "not a GetX issue" explain to me why the hell "file:///home/david/.pub-cache/hosted/pub.dartlang.org/**get-3.13.2**/lib/**get_navigation**/src/root/root_widget.dart:257:22" appears in the log??

anyways, your commands fixed nothing.
The issue persists in the stable channel of flutter, which I mentioned in the OP. Judging by you missing that fact, you didn't even read half of my issue.

**Comment by psrcek** [comment]
I figured it out. My issue was that I was using `onGenerateRoute` and returning a `CustomGetPageRoute` with `transitionDuration` set to null. I guess a GetX update somehow broke that or something as this used to work before.

here's the full implementation that broke it:
```dart
  Route<dynamic> generateRoute(RouteSettings settings) {
    logDebug('generateRoute', settings);

    final match = Get.routeTree.matchRoute(settings.name);
    Get.parameters = match?.parameters;

    if (match?.route == null) {
      return CustomGetPageRoute(
        page: () => RcgPopScope(
          child: _buildErrorPage(errorMessage: 'Nonexistant page: ${settings.name}\n${settings.arguments}'),
        ),
        settings: RouteSettings(name: settings.name, arguments: settings.arguments),
      );
    }

    return CustomGetPageRoute(
      page: match.route.page,
      parameter: match.route.parameter,
      settings: RouteSettings(name: settings.name, arguments: settings.arguments),
      curve: match.route.curve,
      opaque: match.route.opaque,
      customTransition: match.route.customTransition,
      binding: match.route.binding,
      bindings: match.route.bindings,
      transitionDuration: match.route.transitionDuration,
      transition: match.route.transition,
      popGesture: match.route.popGesture,
      fullscreenDialog: match.route.fullscreenDialog,
      maintainState: match.route.maintainState,
    );
  }

```

for my fix I changed `transitionDuration: match.route.transitionDuration,` to `transitionDuration: match.route.transitionDuration ?? const Duration(milliseconds: 400),` in the return.
