### ISSUE TITLE
stuck on Get.updateLocale

### ISSUE THREAD

**Issue by mmmcorpsvit** [jonataslaw/getx#737]
start use you wonderful library. Have dropdown list for select UI language, on change execute code

```dart
class AppLanguageItem {
  const AppLanguageItem(this.name, this.countryCode, this.languageCode);

  final String name;
  final String countryCode;
  final String languageCode;

  @override
  String toString() {
    return name;
  }
}

const List<AppLanguageItem> appLanguagesList = <AppLanguageItem>[
  AppLanguageItem('English', 'en', 'US'),
  AppLanguageItem('Ukrainian', 'uk', 'UA'),
  AppLanguageItem('Russian', 'ru', 'RU')
];

  _setLocale(locale) {
    // find locale by name
    var w = appLanguagesList.firstWhere((element) => element.name == locale);
    Get.updateLocale(Locale(w.countryCode, w.languageCode));
  }
```

stuck at Get.updateLocale, on real device and emulator( can share full source if need, please help. Stuck at random moment, i rely can't understand why. Just stuck, no errors, no crash etc... just quite stuck(

**Comment by eduardoflorence** [comment]
There don't seem to be any errors, but we need to analyze your GetMaterialApp and the Class with the translations. Please share all the source code so that we can reproduce the problem

**Comment by mmmcorpsvit** [comment]
> 
> 
> There don't seem to be any errors, but we need to analyze your GetMaterialApp and the Class with the translations. Please share all the source code so that we can reproduce the problem


[emeet.zip](https://github.com/jonataslaw/getx/files/5462384/emeet.zip)

**Comment by mmmcorpsvit** [comment]
language picker at top of login screen
my code bad (i start use flatter month ago), will be happy if extend and fix how example project)

**Comment by eduardoflorence** [comment]
I just made the changes below and resolved

**language_picker.dart**
```dart
  ...
  @override
  Widget build(BuildContext context) {
    final localeLanguageCode = Get.locale.toString().split('_')[1]; // <- change
    return Container(
        // padding: EdgeInsets.all(20.0),
        alignment: Alignment.topRight,
        child: DropdownButton<String>(
          value: appLanguagesList
              .firstWhere((element) => element.languageCode == localeLanguageCode) // <- change
              .name,
          onChanged: _setLocale,
          items: _languagesList,
        ));
  }
```

**Comment by mmmcorpsvit** [comment]
this not help for me(
i continue testing, and think problem in Get.update inside forceAppUpdate

i just use few finger (debug mode run from android studio)
log:

> 
> Launching lib\main.dart on meizu note9 in debug mode...
> Running Gradle task 'assembleDebug'...
> √ Built build\app\outputs\flutter-apk\app-debug.apk.
> Waiting for meizu note9 to report its views...
> Debug service listening on ws://127.0.0.1:62271/dMom_o2nmLw=/ws
> Syncing files to device meizu note9...
> I/flutter (31800): Injecting dependencies
> [GETX] Lazy instance "FlutterSecureStorage" created
> [GETX] "GetMaterialController" has been initialized
> [GETX] GOING TO ROUTE /login
> [GETX] Lazy instance "LoginController" created
> I/flutter (31800): onInit
> [GETX] "LoginController" has been initialized
> I/flutter (31800): onReady
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> E/flutter (31800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/gestures/binding.dart': Failed assertion: line 227 pos 12: '!locked': is not true.
> E/flutter (31800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> E/flutter (31800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> E/flutter (31800): #2      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:227:12)
> E/flutter (31800): #3      _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (31800): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #7      _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (31800): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (31800): #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (31800): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> E/flutter (31800): #11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (31800): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> E/flutter (31800): 
> 

then app stuck(
in any way i free for change design, will be fine quick fix - any way for safe change languge UI

**Comment by mmmcorpsvit** [comment]
how represent error:-
just use few fingers at screen and dropdown and quick random tap by fingers, bug stable
too i use android studio from debug mode run, but bug happend on release profile too

**Comment by eduardoflorence** [comment]
To do: 
Update Getx in pubspec.yml for 3.15.0. 
In terminal:
``` 
flutter channel stable
flutter upgrade
flutter clean
flutter pub cache repair
flutter pub get
```

**Comment by mmmcorpsvit** [comment]
reinstall all, not help for me, i use windows, you too?

**Comment by eduardoflorence** [comment]
I also use windows

**Comment by mmmcorpsvit** [comment]
hm... can share please you apk, maybe problem in my env(

**Comment by eduardoflorence** [comment]
This is my entire folder:
[emeet.zip](https://github.com/jonataslaw/getx/files/5503579/emeet.zip)

This is the working app:
![emeet](https://user-images.githubusercontent.com/9120528/98417303-76ad8f80-205f-11eb-8ffa-d5b4c03e0901.gif)

**Comment by jonataslaw** [comment]
Can this issue be closed?

**Comment by mmmcorpsvit** [comment]
error present(

**Comment by ArkasDev** [comment]
Same error. When I use `Get.updateLocale` after my API call to get the saved language, the app sometimes gets stuck in the loading screen forever. Without the update, it works fine. When I use the update function only on a button click, it works fine too.

**Comment by jonataslaw** [comment]
Fixed in GetX 5
