### ISSUE TITLE
Can't reinitilize dependuncies bindings when Get.off()

### ISSUE THREAD

**Issue by drashoor** [jonataslaw/getx#757]
**Describe the bug**
I suppose that I can reinitialize the dependencies bindings for some cases ex: Get.off(), like the below example. I want to replace the route not push it.

**Reproduction code

example:

```dart
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: '/register',
      getPages: [
        GetPage(
          name: '/register',
          page: () => RegisterView(),
          binding: AuthBindings(),
        ),
        GetPage(
          name: '/login',
          page: () => LoginView(),
          binding: AuthBindings(),
        ),
      ],
    );
  }
}

class AuthBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => Dio());
    Get.lazyPut(() => AuthRemoteDataSource(dio: Get.find()));
    Get.lazyPut(() => AuthRepository(authRemoteDataSource: Get.find()));
    Get.lazyPut(() => RegisterController(authRepository: Get.find()));
    Get.lazyPut(() => LoginController(authRepository: Get.find()));
  }
}

class RegisterView extends GetView<RegisterController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Call Register'),
              onPressed: () {
                controller.register();
              },
            ),
            RaisedButton(
              child: Text('Goto Login'),
              onPressed: () => Get.off(LoginView()),
            ),
          ],
        ),
      ),
    );
  }
}

class LoginView extends GetView<LoginController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Call Login'),
              onPressed: () {
                controller.login();
              },
            ),
            RaisedButton(
              child: Text('Goto Login'),
              onPressed: () => Get.off(RegisterView()),
            ),
          ],
        ),
      ),
    );
  }
}

class RegisterController extends GetxController {
  RegisterController({this.authRepository});

  final AuthRepository authRepository;

  register() {
    authRepository.register();
  }
}

class LoginController extends GetxController {
  LoginController({this.authRepository});

  final AuthRepository authRepository;

  login() {
    authRepository.login();
  }
}

class AuthRepository {
  AuthRepository({this.authRemoteDataSource});

  final AuthRemoteDataSource authRemoteDataSource;

  login() async {
    return await authRemoteDataSource.login();
  }

  register() async {
    return await authRemoteDataSource.register();
  }
}

class AuthRemoteDataSource {
  AuthRemoteDataSource({this.dio});

  final Dio dio;

  login() async {
    await dio.get('https://www.google.com');
  }

  register() async {
    await dio.get('https://www.google.com');
  }
}

```

**To Reproduce**
1. Click on Call Register
2. Click on Goto Login
3. Click on Call login

**Expected behavior**
Supposed that dependencies are reinitialized, but they are removed from memory and cant be initialized again.

```dart
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,896ms.
[GETX] "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /register
[GETX] Lazy instance "RegisterController" created
[GETX] Lazy instance "AuthRepository" created
[GETX] Lazy instance "AuthRemoteDataSource" created
[GETX] Lazy instance "Dio" created
[GETX] "RegisterController" has been initialized
[GETX] REPLACE ROUTE /register
[GETX] NEW ROUTE /LoginView
[GETX] "Dio" deleted from memory
[GETX] "AuthRemoteDataSource" deleted from memory
[GETX] "AuthRepository" deleted from memory
[GETX] "RegisterController" onClose() called
[GETX] "RegisterController" deleted from memory
[GETX] Lazy instance "LoginController" created

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following message was thrown while handling a gesture:
"AuthRepository" not found. You need to call "Get.put(AuthRepository())" or "Get.lazyPut(()=>AuthRepository())"

When the exception was thrown, this was the stack: 
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:284:9)
#1      Inst.find (package:get/get_instance/src/extension_instance.dart:66:44)
#2      AuthBindings.dependencies.<anonymous closure> (package:getx_sample/main.dart:37:59)
#3      GetInstance.find (package:get/get_instance/src/get_instance.dart:288:50)
#4      GetView.controller (package:get/get_state_manager/src/simple/get_view.dart:36:37)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#270b0
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(173.0, 303.0)
  finalLocalPosition: Offset(40.5, 25.0)
  button: 1
  sent tap down

```

**Flutter Version:**
1.22.2

**Getx Version:**
3.15.0

**Describe on which device you found the bug:**
Emulator

**Comment by drashoor** [comment]
After a lot of attempts I solved this issue, but I want to see your solutions.

:)

**Comment by prakash-indorkar** [comment]
> 
> 
> After a lot of attempts I solved this issue, but I want to see your solutions.
> 
> :)

Hi, could you please share the solution. I am having lot of issues due to this... In my application when I save the form and use Get.off, it deletes all the Controller Instances.. leaving no states in memory apart from dpenedencies where I have used loaded as permamnent. Or something I am doing wrong .. If anyone can share a good example using GetX and Auth with firebase and storage, along with a simple crud, like a blog.. with post and comments stream. Using GetX folder structure. Please help, I am strugling to use GetX full fledged.
Thanks in advance, Prakash

**Comment by eduardoflorence** [comment]
AuthRemoteDataSource, AuthRepository, RegisterController and LoginController must extend GetxService and not GetxController.
GetxService can not be removed from memory.
See: https://github.com/jonataslaw/getx#getxservice

**Comment by eduardoflorence** [comment]
If you don't want to use GetxService, an alternative is to use the `fenix` property of the lazyPut method. For example:

```dart
class AuthBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => Dio(), fenix: true);
    Get.lazyPut(() => AuthRemoteDataSource(dio: Get.find()), fenix: true);
    Get.lazyPut(() => AuthRepository(authRemoteDataSource: Get.find()), fenix: true);
    Get.lazyPut(() => RegisterController(authRepository: Get.find()), fenix: true);
    Get.lazyPut(() => LoginController(authRepository: Get.find()), fenix: true);
  }
}
```

fenix is similar to "permanent" (Get.put property), the difference is that the instance is discarded when is not being used, but when it's use is needed again, Get will recreate the instance.

**Comment by prakash-indorkar** [comment]
Hi I’m sharing my code.. please if you can just have a quick look and let me know how can I improve.. I am not using repositories, providers .. because I am yet to understand how to distinguish in them.. I’m actually using MVC pattern only .. I am waiting for a good example on GetX package, so that I can understand what goes where, and differentiate repository, service, controller and repositories.

Please have a look, lots of thanks again.
https://prod.liveshare.vsengsaas.visualstudio.com/join?B1B35782779A75E67C3636AE44A4CFF9EDFE

Regards, Prakash

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mrgithub** [comment]
How can you force the controller to be deleted and recreated/reinitialised on command?

**Comment by jonataslaw** [comment]
Do not use Get.off, but Get.offNamed if you are using named routes.
Use the fenix parameter if you want the controller to reboot after deleting.
Since I couldn't find a problem in the code presented, I'm closing this
