### ISSUE TITLE
[GetConnect] Allow optional for body argument in Post method

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#828]
I was using Dio and plan to migrate to newly introduce GetConnect.
I have encountered the following exception for Post method when body is null. 
Can we make the body argument optional?

One more thing, I would expect GetConnect will catch the exception and return me the Response with hasError = true, but it seems will get stuck there.

Thanks.

~~~Dart
E/flutter ( 6768): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:get/get_connect/http/src/http.dart': Failed assertion: line 254 pos 12: 'body != null': is not true.
[38;5;244mE/flutter ( 6768): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)[39;49m
[38;5;244mE/flutter ( 6768): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)[39;49m
[38;5;248mE/flutter ( 6768): #2      GetHttpClient._post[39;49m
 package:get/…/src/http.dart
[38;5;248mE/flutter ( 6768): #3      GetHttpClient.post.<anonymous closure>[39;49m
 package:get/…/src/http.dart
[38;5;248mE/flutter ( 6768): #4      GetHttpClient._performRequest[39;49m
 package:get/…/src/http.dart
[38;5;248mE/flutter ( 6768): #5      GetHttpClient.post[39;49m
 package:get/…/src/http.dart
[38;5;248mE/flutter ( 6768): #6      GetConnect.post[39;49m
 package:get/get_connect/connect.dart
[38;5;248mE/flutter ( 6768): #7      AppConnectService.post[39;49m
 package:viqcorex/…/app/app_connect.dart
[38;5;248mE/flutter ( 6768): #8      Discussion.postLike[39;49m
 package:viqcommunity/…/src/discussion.dart
[38;5;248mE/flutter ( 6768): #9      DiscussionListController.postLikeUnlike[39;49m
 package:viqcommunity/…/controllers/discussion_list_controller.dart
[38;5;248mE/flutter ( 6768): #10     DiscussionItem.buildActionButtons.<anonymous closure>.<anonymous closure>[39;49m
 package:viqcommunity/…/src/discussion_item.dart
[38;5;244mE/flutter ( 6768): #11     _InkResponseState._handleTap[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244mE/flutter ( 6768): #12     _InkResponseState.build.<anonymous closure>[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244mE/flutter ( 6768): #13     GestureRecognizer.invokeCallback[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244mE/flutter ( 6768): #14     TapGestureRecognizer.handleTapUp[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter ( 6768): #15     BaseTapGestureRecognizer._checkUp[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter ( 6768): #16     BaseTapGestureRecognizer.acceptGesture[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter ( 6768): #17     GestureArenaManager.sweep[39;49m
 package:flutter/…/gestures/arena.dart
[38;5;244mE/flutter ( 6768): #18     GestureBinding.handleEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 6768): #19     GestureBinding.dispatchEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 6768): #20     RendererBinding.dispatchEvent[39;49m
 package:flutter/…/rendering/binding.dart
[38;5;244mE/flutter ( 6768): #21     GestureBinding._handlePointerEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 6768): #22     GestureBinding._flushPointerEventQueue[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 6768): #23     GestureBinding._handlePointerDataPacket[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 6768): #24     _rootRunUnary (dart:async/zone.dart:1206:13)[39;49m
[38;5;244mE/flutter ( 6768): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 6768): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)[39;49m
[38;5;244mE/flutter ( 6768): #27     _invoke1 (dart:ui/hooks.dart:265:10)[39;49m
[38;5;244mE/flutter ( 6768): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)[39;49m
E/flutter ( 6768):
~~~

**Comment by jonataslaw** [comment]
Fixed on lastest version
