### ISSUE TITLE
[GetConnect] GET method with Query map has number type

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#857]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When perform a GET method call, it hits error when the query has int type. Same code works well with dio.

![image](https://user-images.githubusercontent.com/107820/101240974-97840600-372d-11eb-996c-48f2cc22723f.png)

~~~dart
[38;5;244m[GETX] [39;49mGOING TO ROUTE /discussion_list
[38;5;244m[GETX] [39;49m"DiscussionListController" has been initialized
[38;5;244m[GETX] [39;49mOPEN SNACKBAR
E/flutter (25035): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<bool>'
[38;5;244mE/flutter (25035): #0      _FutureListener.handleError (dart:async/future_impl.dart:160:20)[39;49m
[38;5;244mE/flutter (25035): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)[39;49m
[38;5;244mE/flutter (25035): #2      Future._propagateToListeners (dart:async/future_impl.dart:729:24)[39;49m
[38;5;244mE/flutter (25035): #3      Future._completeError (dart:async/future_impl.dart:537:5)[39;49m
[38;5;244mE/flutter (25035): #4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)[39;49m
[38;5;244mE/flutter (25035): #5      _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244mE/flutter (25035): #6      _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244mE/flutter (25035): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)[39;49m
[38;5;244mE/flutter (25035): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)[39;49m
[38;5;244mE/flutter (25035): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244mE/flutter (25035): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)[39;49m
E/flutter (25035):
[38;5;244m[GETX] [39;49mOPEN SNACKBAR
E/flutter (25035): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<bool>'
[38;5;244mE/flutter (25035): #0      _FutureListener.handleError (dart:async/future_impl.dart:160:20)[39;49m
[38;5;244mE/flutter (25035): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)[39;49m
[38;5;244mE/flutter (25035): #2      Future._propagateToListeners (dart:async/future_impl.dart:729:24)[39;49m
[38;5;244mE/flutter (25035): #3      Future._completeError (dart:async/future_impl.dart:537:5)[39;49m
[38;5;244mE/flutter (25035): #4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)[39;49m
[38;5;244mE/flutter (25035): #5      _rootRun (dart:async/zone.dart:1190:13)[39;49m
[38;5;244mE/flutter (25035): #6      _CustomZone.run (dart:async/zone.dart:1093:19)[39;49m
[38;5;244mE/flutter (25035): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)[39;49m
[38;5;244mE/flutter (25035): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)[39;49m
[38;5;244mE/flutter (25035): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244mE/flutter (25035): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)[39;49m
~~~

**Expected behavior**
Tested by manually converting the int type to string solve the problem. However, I would expect the package should do the conversion to string.

**Flutter Version:**
1.22.4

**Getx Version:**
3.22.2

**Describe on which device you found the bug:**
ex: Emulator - Android.

**Comment by eduardoflorence** [comment]
I think the error presented is not related to the `query` parameter. The return of `request` is a `FutureOr<bool>`, but the `requestForDio` function expects `Future<Response>`.

**Comment by jasonlaw** [comment]
> I think the error presented is not related to the `query` parameter. The return of `request` is a `FutureOr<bool>`, but the `requestForDio` function expects `Future<Response>`.

You are right, that was my mistake in handling the error.
However, the issue is still valid. Here is the correct error:

**E/flutter ( 5906): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'Iterable<dynamic>'
E/flutter ( 5906):**

**Comment by eduardoflorence** [comment]
@jasonlaw, this is not a problem with GetX. Getx uses the Dart/Flutter `URI` class to build the request URL. Look at what I found in the Flutter source code:
```dart
Uri replace(
      {String? scheme,
      String? userInfo,
      String? host,
      int? port,
      String? path,
      Iterable<String>? pathSegments,
      String? query,
      Map<String, dynamic /*String|Iterable<String>*/ >? queryParameters,
      String? fragment});
```
Although queryParameter is typed with `Map<String, dynamic>`, there is a comment that dynamic must be `String | Iterable <String>`, so it does not support integers
