### ISSUE TITLE
"BoxConstraints forces an infinite width" when adding mainButton to snackBar

### ISSUE THREAD

**Issue by alizera** [jonataslaw/getx#919]
I'm using the following code to show snack bar:
```
    Get.snackbar(
      title ?? S.current.error,
      message ?? '',
      colorText: Colors.white,
      snackPosition: _snackPosition,
      backgroundColor: Colors.red.withRed(255).withAlpha(100),
      duration: duration,
      icon: Icon(iconData ?? Icons.warning_amber_rounded),
      shouldIconPulse: true,
      onTap: (_) => print('onTap: $_'),
      mainButton: FlatButton(onPressed: (){print('something');}, child: Text('action')) // Error line
    );
```
Without adding `mainButton` everything looks good but by adding it, get doesn't show snack bar and console shows tons of errors:
```
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite width.

These invalid constraints were provided to RenderCustomPaint's layout() function by the following function, which probably computed the invalid constraints in question:
  RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
The offending constraints were: BoxConstraints(w=Infinity, 50.0<=h<=Infinity)
The relevant error-causing widget was: 
  FlatButton file:///Users/newuser/apps/flutter/pay98/lib/app/utils/ui_util.dart:58:19
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:559:21)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:565:6)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1677:24)
#4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
...
The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#4dc4c relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: MISSING
...  additionalConstraints: BoxConstraints(w=Infinity, 50.0<=h<=Infinity)
RenderObject: RenderConstrainedBox#4dc4c relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(unconstrained)
  size: MISSING
  additionalConstraints: BoxConstraints(w=Infinity, 50.0<=h<=Infinity)
...  child: RenderCustomPaint#2e62d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none>
...    constraints: MISSING
...    size: MISSING
...    child: _RenderInkFeatures#97254 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      child: RenderSemanticsAnnotations#6b358 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        child: RenderMouseRegion#d07e7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RenderBox was not laid out: RenderConstrainedBox#4dc4c relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1785 pos 12: 'hasSize'
The relevant error-causing widget was: 
  FlatButton file:///Users/newuser/apps/flutter/pay98/lib/app/utils/ui_util.dart:58:19
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jonataslaw** [comment]
This issue has nothing to do with GetX, the error says that you are inserting a widget without vertical constraint, just check the line that this occurs and correct the problem in your code.
In addition, I tested this code and it works perfectly without any error, so I am closing it.

```dart
 Get.snackbar('foo', 'bar',
                    colorText: Colors.white,
                    backgroundColor: Colors.red.withRed(255).withAlpha(100),
                    icon: Icon(Icons.warning_amber_rounded),
                    shouldIconPulse: true,
                    onTap: (_) => print('onTap: $_'),
                    mainButton: FlatButton(
                        onPressed: () {
                          print('something');
                        },
                        child: Text('action')) // Error line
                    );
              },
              child: Text('open snackbar'),
```
