### ISSUE TITLE
[GetConnect] Error: "Stream has already been listened to." When trying to upload a file.

### ISSUE THREAD

**Issue by pratamatama** [jonataslaw/getx#930]
**Describe the bug**
Unable to upload a file either using `post` or `put` with `GetConnect`.

<details>
<summary>Stacktrace (click to expand)</summary>

```
E/flutter (30324): #5      _StreamController.addStream (dart:async/stream_controller.dart:600:9)
E/flutter (30324): #6      _AsyncStarStreamController.addStream (dart:async-patch/async_patch.dart:216:37)
E/flutter (30324): #7      FormData._encode
package:get/…/multipart/form_data.dart:110
E/flutter (30324): <asynchronous suspension>
E/flutter (30324): #8      FormData.toBytes
package:get/…/multipart/form_data.dart:92
E/flutter (30324): #9      GetHttpClient._requestWithBody
package:get/…/src/http.dart:103
E/flutter (30324): #10     GetHttpClient._post
package:get/…/src/http.dart:261
E/flutter (30324): #11     GetHttpClient.post.<anonymous closure>
package:get/…/src/http.dart:341
E/flutter (30324): #12     GetHttpClient._performRequest
package:get/…/src/http.dart:181
E/flutter (30324): #13     GetHttpClient._performRequest
package:get/…/src/http.dart:197
E/flutter (30324): <asynchronous suspension>
E/flutter (30324): #14     GetHttpClient.post
package:get/…/src/http.dart:340
E/flutter (30324): #15     GetConnect.post
package:get/get_connect/connect.dart:133
E/flutter (30324): #16     AuthProvider.updateAvatar
package:prismahr/…/auth/auth_provider.dart:21
E/flutter (30324): #17     AuthRepository.updateAvatar
package:prismahr/…/repositories/auth_repository.dart:26
E/flutter (30324): #18     ProfilePersonalController.changeAvatar
package:prismahr/…/controllers/profile_personal_controller.dart:35
E/flutter (30324): <asynchronous suspension>
E/flutter (30324): #19     _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter (30324): #20     _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter (30324): #21     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (30324): #22     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (30324): #23     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (30324): #24     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:259
E/flutter (30324): #25     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
E/flutter (30324): #26     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:362
E/flutter (30324): #27     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter (30324): #28     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter (30324): #29     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter (30324): #30     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter (30324): #31     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter (30324): #32     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (30324): #33     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30324): #34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (30324): #35     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (30324): #36     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (30324):

```
</details>

**Reproduction code**

`profile_personal_controller.dart`
```dart
final uploading = false.obs;
Future<void> changeAvatar() async {
  final img = await ImagePicker().getImage(source: ImageSource.gallery);
  if (img.isNull) return;

  uploading.toggle();
  final response = await Get.find<AuthRepository>().updateAvatar(
    await img.readAsBytes(),
    basename(img.path),
  );

  uploading.toggle();
  if (response.hasError) return handleAvatarUploadError(response);
  ...
}
```

`auth_repository.dart`
```dart
Future<Response> updateAvatar(List<int> img, String filename) {
  return provider.updateAvatar(img, filename);
}
```

`auth_provider.dart`

```dart
Future<Response> updateAvatar(List<int> img, String filename) {
  final avatar = MultipartFile(img, filename: filename);

  // return put('auth/user', FormData({'avatar', avatar}));

  return post('auth/user/avatar', FormData({'avatar': avatar}));
}
```

**To Reproduce**
1. Create new getx project
2. Add `image_picker` dependency into `pubspec.yaml`
3. Create files and copy contents above
4. Create one view with upload button
5. Attach `changeAvatar` method into the button
6. Click the button, choose an image
7. See error

**Expected behavior**
The given request should be sent to the server, and file is uploaded.

**Screenshots**

`source`
![image](https://user-images.githubusercontent.com/42239243/102692348-4bfd4c00-4245-11eb-9290-d627d8d43ef3.png)

`debug: step out 1x`
![image](https://user-images.githubusercontent.com/42239243/102691774-8c5acb00-4241-11eb-8a7a-001f3a0217dd.png)

**Flutter Version:**
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (9 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Getx Version:**
`get: ^3.22.2`

**Describe on which device you found the bug:**
Xiaomi Redmi Note 7 (Lavender) - Android 10

**Comment by rakeshlanjewar** [comment]
@jonataslaw Please help

**Comment by rakeshlanjewar** [comment]
@pratamatama Did you find the solution ?

**Comment by pratamatama** [comment]
@rakeshlanjewar unfortunately no. I'm switching back to dio for this project

**Comment by diego-lipinski-de-castro** [comment]
I got into this problem and reloading the app state solved

**Comment by jonataslaw** [comment]
Just update the version of Getx, this error happened only with a specific version that had a hotfix immediately (and you are using it)
