### ISSUE TITLE
Unhandled Exception: You are trying to use contextless navigation

### ISSUE THREAD

**Issue by ajaygautam** [jonataslaw/getx#976]
Trying to introduce the getx library into my app.

At line `Get.off(IntroScreen());` I get the following error:
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: You are trying to use contextless navigation without
      a GetMaterialApp or Get.key.
      If you are testing your app, you can use:
      [Get.testMode = true], or if you are running your app on
      a physical device or emulator, you must exchange your [MaterialApp]
      for a [GetMaterialApp].

#0      GetNavigation.global (package:get/get_navigation/src/extension_navigation.dart:995:7)
#1      GetNavigation.off (package:get/get_navigation/src/extension_navigation.dart:817:12)
```

The error message does not describe how to use `Get.key`.

PS: I cannot use `GetMaterialApp` because I want a iOS compatible app too. So... I am using `PlatformApp` from `flutter_platform_widgets`. Can't figure out how to use `GetMaterialApp` with `PlatformApp`... so my choice is to use `Get.key`. Please advice how to use `Get.key`.

Reproduction code
```dart
void main() => runApp(IgApp());

class IgApp extends StatefulWidget {
  @override
  IgAppState createState() => IgAppState();
}

class IgAppState extends State<IgApp> {
  final AppNavigationObserver appNavigationObserver = AppNavigationObserver();

  Widget build(BuildContext context) {
    return MultiBlocProvider(
        providers: [
          BlocProvider<AccountBloc>(create: (context) => AccountBloc(sl())),
          BlocProvider<AppSettingsBloc>(create: (context) => sl())
        ],
        child: BlocBuilder<AppSettingsBloc, AppState>(builder: (context, appState) {
          return Material(
              color: appState.visualData.backgroundColor,
              child: PlatformApp(
                  localizationsDelegates: <LocalizationsDelegate<dynamic>>[
                    DefaultMaterialLocalizations.delegate,
                    DefaultWidgetsLocalizations.delegate,
                    DefaultCupertinoLocalizations.delegate
                  ],
                  debugShowCheckedModeBanner: false,
                  navigatorObservers: [appNavigationObserver],
                  title: appTitle,
                  material: (_, __) => appState.visualData.materialAppData,
                  cupertino: (_, __) => new CupertinoAppData(theme: appState.visualData.cupertinoTheme),
                  home: HomeOrIntroScreen()));
        }));
  }
}

class HomeOrIntroScreen extends StatefulWidget {
  @override
  HomeOrIntroScreenState createState() => new HomeOrIntroScreenState();
}

class HomeOrIntroScreenState extends State<HomeOrIntroScreen> with AfterLayoutMixin<HomeOrIntroScreen> {
  static final introScreenSeen = 'seen';

  Future checkIntroScreenSeen() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    bool _seen = (prefs.getBool(introScreenSeen) ?? false);

    if (_seen) {
      _log.info("Intro Screen has been seen already. Taking user to Home!");
//      Get.off(PlatformHomePage());
    } else {
      _log.info("Intro Screen: Setting value of _seen found to be true");
      // await prefs.setBool(introScreenSeen, true); // TODO
      Get.off(IntroScreen());
    }
  }

  @override
  void afterFirstLayout(BuildContext context) {
    checkIntroScreenSeen();
  }

  @override
  Widget build(BuildContext context) {
    return Container(alignment: Alignment.center, child: Center(child: PlatformText("Loading...")));
  }
}
```

**To Reproduce**
Run the app with code above

**Expected behavior**
App runs

**Getx Version:** `get: ^3.24.0`

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.25.0-8.1.pre at /Users/agautam/tools/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/agautam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • agipe (mobile)             • 00008030-000260C202C0802E            • ios • iOS 14.3
    • iPhone 12 Pro Max (mobile) • D52F7EE5-34D4-4444-B05E-743F72B240A9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!
```

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx#optional-global-settings-and-manual-configurations
